<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Introduction to Python programming for data journalism – Daniel’s Data Stories</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-cd884f2855776405ca61470c593c983e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Daniel’s Data Stories</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/dpark2380/comm3180_S26_Blog"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Introduction to Python programming for data journalism</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="comm3180-spring-2026" class="level2">
<h2 class="anchored" data-anchor-id="comm3180-spring-2026">COMM3180 Spring 2026</h2>
<section id="instructor-matt-odonnell-mbodasc.upenn.edu" class="level3">
<h3 class="anchored" data-anchor-id="instructor-matt-odonnell-mbodasc.upenn.edu">Instructor: Matt O’Donnell (mbod@asc.upenn.edu)</h3>
</section>
<section id="course-overview" class="level3">
<h3 class="anchored" data-anchor-id="course-overview">Course Overview</h3>
<ul>
<li>This notebook uses a dataset from OpenDataPhilly on vehicular crashes to demonstrate the range of analytic techniques and programming skills we will learn in this course.</li>
</ul>
<hr>
</section>
</section>
<section id="why-learn-programming-and-data-analysis-skills-for-making-stories-from-data" class="level1">
<h1>Why learn programming and data analysis skills for making stories from data?</h1>
<section id="testing-data-in-stories-finding-stories-in-data-and-making-stories-from-data" class="level2">
<h2 class="anchored" data-anchor-id="testing-data-in-stories-finding-stories-in-data-and-making-stories-from-data"><em>Testing</em> data in stories, <br> <em>finding</em> stories in data and <br> <em>making</em> stories from data</h2>
<ul>
<li><p>In the era of <em>big data</em> we frequently encounter stories in various forms of media that make assertions and claim to be based on the analysis of large datasets. It is often possible to access and analyze the data of relevance behind these stories. This allows us, for example, to test the claims, the focus and framing of a news article reporting. While there a number of online tools to explore and visualize open datasets, developing programming skills will allow you greater flexibility and the ability to filter, group and combine data in anticipated and unsupported ways.</p></li>
<li><p>As more and more data is available it becomes vital for more people to acquire and spread the skills for handling these data beyond just a handful of data storytelling experts and media sources. There has been lots of discussion of <em>open data</em> and <em>data democratization</em> (both within private and public realms) espousing the benefits of making data available to “everyone” beyond its traditional management and analysis by IT departments and statisticians. One element of this is making the data available and easily accessible. But equally (if not <em>more</em> ) important than this is having ability to analytically handle these datasets. While it would be a mistake to suggest that learning programming <strong>and</strong> data analysis is a trivial or quick thing to do. It is certainly not beyond the reach of motivated individuals and there are many resources available to teach programming languages, such as Python and R. One might even argue that it is the responsibility of modern citizens to become data literate and this should include acquiring some basic data analysis and programming skills.</p></li>
<li><p>Having the ability to acquire, analyze and to discover and interpret patterns in data means that more stories can be told beyond the core of those selected by traditional media sources for broad appeal, political, commercial and other reasons.</p></li>
<li><p>As students of communication theory we know that effective and persuasive communication is not just about sharing the right (or true) information but also about how you select from, order and present (frame) this information. This becomes all the more crucial as the amount data increases. A fundamental skill for telling stories from data is first being able to identify the stories <strong>in</strong> data. These might be found by describing and summarizing what is there, identifying trends over time or in making comparisons between different groups, categories and factors, and so on. These stories in data then become the components of the larger story you can tell from the data.</p></li>
<li><p>Data journalism or data storytelling requires skills in:</p>
<ul>
<li>some programming</li>
<li>data analysis and visualization</li>
<li>identifying patterns (stories) in data</li>
<li>telling stories from these patterns</li>
</ul></li>
</ul>
</section>
</section>
<section id="example-analyzing-vehicular-crash-data-for-philadelphia-2005-2025" class="level1">
<h1>Example: Analyzing vehicular crash data for Philadelphia 2005-2025</h1>
<ul>
<li><p>The remainder of this notebook will work through an example of exploring and analyzing an open public dataset using <code>pandas</code>, the core Python tool we will learn in this class. It works through the key steps:</p>
<ol type="1">
<li>Acquiring and loading a dataset</li>
<li>Inspecting and understanding the data</li>
<li>Looking at metadata and turning data into information</li>
<li>Exploring the relevant and interesting components of the dataset</li>
<li>Grouping and associating the data to find patterns and trends</li>
<li>Communicating these insights in an engaging story.</li>
</ol>
<p>We will return to and practice these steps again and again in this course.</p></li>
<li><p>Here we make use of data made available on www.opendataphilly.org</p>
<p><img src="img/openphilly.png" class="img-fluid"></p></li>
<li><p>The particular dataset is derived from the annual crash data compiled by Penn DOT for Pennsylvania.</p>
<ul>
<li>https://www.opendataphilly.org/dataset/vehicular-crash-data <img src="img/penndot.png" class="img-fluid"></li>
</ul></li>
</ul>
<section id="setup-notebook" class="level3">
<h3 class="anchored" data-anchor-id="setup-notebook">0. Setup notebook</h3>
<ul>
<li><p>The first Python code in a notebook should include all the modules and functions that you need to use for the analysis. These are grouped together at the top and not scattered throughout the notebook to make it clearer and more reproducible.</p></li>
<li><p>For data analysis we are going to use a popular and powerful code library called <code>pandas</code> (https://pandas.pydata.org/) that provides data structures and functionality optimized for data analysis and particularly for working with data in the form of a table.</p></li>
</ul>
<div id="cell-5" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> geopandas <span class="im">as</span> gpd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> camelot</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> calendar</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> re</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="load-the-data" class="level3">
<h3 class="anchored" data-anchor-id="load-the-data">1. Load the data</h3>
<ul>
<li><p>We will look at some of the most common data formats used to store data in files. Here we have downloaded the <strong>CSV</strong> (<em>comma separated value</em>) format version of the vehicular crash data.</p></li>
<li><p>Here is a subset of the data with 7 recorded crashes and a small handful of the features recorded about each crash:</p></li>
</ul>
<pre><code>  &lt;th&gt;county_name&lt;/th&gt;      &lt;th&gt;collision_type&lt;/th&gt;      &lt;th&gt;dec_lat&lt;/th&gt;      &lt;th&gt;dec_long&lt;/th&gt;    &lt;/tr&gt;  &lt;/thead&gt;  &lt;tbody&gt;    &lt;tr&gt;      &lt;td&gt;3&lt;/td&gt;      &lt;td&gt;Philadelphia&lt;/td&gt;      &lt;td&gt;1&lt;/td&gt;      &lt;td&gt;40.0446&lt;/td&gt;      &lt;td&gt;-75.0547&lt;/td&gt;    &lt;/tr&gt;    &lt;tr&gt;      &lt;td&gt;5&lt;/td&gt;      &lt;td&gt;Philadelphia&lt;/td&gt;      &lt;td&gt;4&lt;/td&gt;      &lt;td&gt;39.9693&lt;/td&gt;      &lt;td&gt;-75.1432&lt;/td&gt;    &lt;/tr&gt;    &lt;tr&gt;      &lt;td&gt;7&lt;/td&gt;      &lt;td&gt;Philadelphia&lt;/td&gt;      &lt;td&gt;4&lt;/td&gt;      &lt;td&gt;40.0490&lt;/td&gt;      &lt;td&gt;-75.0707&lt;/td&gt;    &lt;/tr&gt;    &lt;tr&gt;      &lt;td&gt;6&lt;/td&gt;      &lt;td&gt;Philadelphia&lt;/td&gt;      &lt;td&gt;6&lt;/td&gt;      &lt;td&gt;39.9034&lt;/td&gt;      &lt;td&gt;-75.1504&lt;/td&gt;    &lt;/tr&gt;    &lt;tr&gt;      &lt;td&gt;4&lt;/td&gt;      &lt;td&gt;Philadelphia&lt;/td&gt;      &lt;td&gt;1&lt;/td&gt;      &lt;td&gt;40.0512&lt;/td&gt;      &lt;td&gt;-74.9892&lt;/td&gt;    &lt;/tr&gt;    &lt;tr&gt;      &lt;td&gt;6&lt;/td&gt;      &lt;td&gt;Philadelphia&lt;/td&gt;      &lt;td&gt;8&lt;/td&gt;      &lt;td&gt;39.9352&lt;/td&gt;      &lt;td&gt;-75.1542&lt;/td&gt;    &lt;/tr&gt;    &lt;tr&gt;      &lt;td&gt;4&lt;/td&gt;      &lt;td&gt;Philadelphia&lt;/td&gt;      &lt;td&gt;4&lt;/td&gt;      &lt;td&gt;40.0811&lt;/td&gt;      &lt;td&gt;-75.0391&lt;/td&gt;    &lt;/tr&gt;  &lt;/tbody&gt;&lt;/table&gt;</code></pre><ul>
<li><p>The CSV format is a simple text format organized with one line for each instance (i.e.&nbsp;a crash) and each feature or data point about the crash (i.e.&nbsp;number of people involved, time of day, kind of injuries, etc.) is separated by a comma. The first line of the file usually contains the names of features.</p></li>
<li><p>A CSV representation of the table above is:</p></li>
</ul><pre><code>day_of_week,county_name,collision_type,dec_lat,dec_long
3,Philadelphia,1,40.0446,-75.0547
5,Philadelphia,4,39.9693,-75.1432
7,Philadelphia,4,40.049,-75.0707
6,Philadelphia,6,39.9034,-75.1504
4,Philadelphia,1,40.0512,-74.9892
6,Philadelphia,8,39.9352,-75.1542
4,Philadelphia,4,40.0811,-75.0391</code></pre><section id="key-point-and-observations" class="level4">
<h4 class="anchored" data-anchor-id="key-point-and-observations"><em>Key point and observations</em></h4>
<ul>
<li><p>A <strong>fundamental point</strong> to take on right at the beginning is that it is here in things a mundane as the data format that we begin to look for the stories in data. It is easy to rush through the steps of acquiring and loading a big data set in order to push it through a data analysis and visualization pipeline or tool, without stopping to think about what each row and column represents.</p>
<ul>
<li>Here <em>each row is an incidence of a crash</em>, which for the individuals involved is a major and serious life event and sadly perhaps a life threatening or life ending event. This event is a story located a particular time and place.</li>
<li>Then the columns represent the <em>potential narrative foci</em> as we begin to group together one, two, ten, 300, thousands of these crash incidents. We can begin to formulate these as questions:
<ul>
<li>What times of day do crashes most often occur?</li>
<li>Are there particularly intersections where a lot of crashes occur?</li>
<li>When a bicycle is involved are the injuries more serious then two or more cars?</li>
</ul></li>
</ul></li>
</ul>
</section><section id="load-the-data-1" class="level3">
<h3 class="anchored" data-anchor-id="load-the-data-1">Load the data</h3>
<ul>
<li><p>We use the <code>pd.read_csv()</code> function to read the data from the CSV file into a data structure called a <strong>data frame</strong>.</p></li>
<li><p>A data frame is a table structure with:</p>
<ul>
<li><code>Rows</code> (each line in the CSV file, i.e.&nbsp;a crash)</li>
<li><code>Columns</code> (each of the features recorded in the CSV file about crashes)</li>
<li><code>An index</code> (a unique way of identifying and accessing each of the rows)</li>
</ul></li>
</ul>
<div id="cell-8" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>crash_data <span class="op">=</span> pd.read_csv(<span class="st">'data/PDOT_crash_data_2005_2024.csv'</span>, low_memory<span class="op">=</span><span class="va">False</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section><section id="inspect-the-data" class="level3">
<h3 class="anchored" data-anchor-id="inspect-the-data">2. Inspect the data</h3>
<ul>
<li><p>The first step is always to try to get a sense of the size (dimensions), type and quality of the data.</p></li>
<li><p>Key questions include:</p>
<ul>
<li><p>How many rows (observations) does it have?</p></li>
<li><p>How many columns (different types of features) are there?</p></li>
<li><p>How comprehensive and varied are these features across the dataset?</p>
<ul>
<li>For example, there may be a column that records whether a deer is involved in the crash. But for Philadelphia city crashes this is likely to most often be 0 or not recorded. And it is therefore probably not the story we are going to tell!</li>
</ul></li>
<li><p>Are there missing values?</p></li>
</ul></li>
<li><p>A pandas <code>DataFrame</code> is a Python <strong>OBJECT</strong> that has:</p>
<ul>
<li><strong>attributes</strong> - sequences of data</li>
<li><strong>functions</strong> - sets of operations or steps that can be applied to these data</li>
</ul></li>
</ul>
<p>(do not worry about this terminology or what it means at the moment!)</p>
<ul>
<li>The <code>.shape</code> attribute gives the dimensions of the <code>DataFrame</code> and reports the number of rows first, followed by the number of columns.</li>
</ul>
<div id="cell-10" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>crash_data.shape</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<pre><code>(691069, 99)</code></pre>
</div>
</div>
<section id="key-point" class="level4">
<h4 class="anchored" data-anchor-id="key-point"><em>Key point</em></h4>
<ul>
<li>So we have almost 700,000 accidents involving vehicles recorded in a 19 year period.
<ul>
<li>That is a large number!</li>
<li>There are stories to be told.</li>
<li>Don’t forget the human side of what these numbers represent.</li>
</ul></li>
<li>There are 99 columns. So each crash incident had a range of features noted. Understanding what these features are is vital to being able to find the stories in the data.</li>
</ul>
</section>
<section id="doing-some-visual-data-inspection" class="level4">
<h4 class="anchored" data-anchor-id="doing-some-visual-data-inspection">Doing some visual data inspection</h4>
<ul>
<li><p>The size of the data necessitates that we approach it computationally and quantitatively, that is, we cannot try and read it row by row! However, it is good practice to do some visual spot checks as a way to familiarize yourself with the data.</p></li>
<li><p>Pandas <code>DataFrame</code>s have various functions for this:</p>
<ol type="1">
<li><code>.head()</code> will display the first <code>n</code> rows of the data frame (default n=5).</li>
<li><code>.tail()</code> will display the last <code>n</code> rows of the data (default n=5).</li>
<li><code>.sample(n)</code> will select a random sample of <code>n</code> rows of the data.</li>
</ol></li>
</ul>
<div id="cell-12" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>crash_data.head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

</div></div></div></section></section><table class="dataframe table table-sm table-striped small">
<thead>
<tr>
<th>
day_of_week
</th>






</tr></thead></table><table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">CRN</th>
<th data-quarto-table-cell-role="th">ARRIVAL_TM</th>
<th data-quarto-table-cell-role="th">AUTOMOBILE_COUNT</th>
<th data-quarto-table-cell-role="th">BELTED_DEATH_COUNT</th>
<th data-quarto-table-cell-role="th">BELTED_SUSP_SERIOUS_INJ_COUNT</th>
<th data-quarto-table-cell-role="th">BICYCLE_COUNT</th>
<th data-quarto-table-cell-role="th">BICYCLE_DEATH_COUNT</th>
<th data-quarto-table-cell-role="th">BICYCLE_SUSP_SERIOUS_INJ_COUNT</th>
<th data-quarto-table-cell-role="th">BUS_COUNT</th>
<th data-quarto-table-cell-role="th">CHLDPAS_DEATH_COUNT</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">WORK_ZONE_LOC</th>
<th data-quarto-table-cell-role="th">WORK_ZONE_TYPE</th>
<th data-quarto-table-cell-role="th">WZ_CLOSE_DETOUR</th>
<th data-quarto-table-cell-role="th">WZ_FLAGGER</th>
<th data-quarto-table-cell-role="th">WZ_LAW_OFFCR_IND</th>
<th data-quarto-table-cell-role="th">WZ_LN_CLOSURE</th>
<th data-quarto-table-cell-role="th">WZ_MOVING</th>
<th data-quarto-table-cell-role="th">WZ_OTHER</th>
<th data-quarto-table-cell-role="th">WZ_SHLDER_MDN</th>
<th data-quarto-table-cell-role="th">WZ_WORKERS_INJ_KILLED</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>2005000003</td>
<td>NaN</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>2005000044</td>
<td>NaN</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>2005000073</td>
<td>NaN</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>2005001018</td>
<td>NaN</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>2005001021</td>
<td>NaN</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

<p>5 rows × 99 columns</p>
</section></section></main></div>


<ul>
<li><p>Notice that because there are 100 columns in the data frame only the first and last ten are displayed (<code>...</code> indicates where the other 70 are).</p></li>
<li><p>By default the columns are shown in the order they appear in the underlying CSV file.</p></li>
</ul>
<div id="cell-14" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>crash_data.tail()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">CRN</th>
<th data-quarto-table-cell-role="th">ARRIVAL_TM</th>
<th data-quarto-table-cell-role="th">AUTOMOBILE_COUNT</th>
<th data-quarto-table-cell-role="th">BELTED_DEATH_COUNT</th>
<th data-quarto-table-cell-role="th">BELTED_SUSP_SERIOUS_INJ_COUNT</th>
<th data-quarto-table-cell-role="th">BICYCLE_COUNT</th>
<th data-quarto-table-cell-role="th">BICYCLE_DEATH_COUNT</th>
<th data-quarto-table-cell-role="th">BICYCLE_SUSP_SERIOUS_INJ_COUNT</th>
<th data-quarto-table-cell-role="th">BUS_COUNT</th>
<th data-quarto-table-cell-role="th">CHLDPAS_DEATH_COUNT</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">WORK_ZONE_LOC</th>
<th data-quarto-table-cell-role="th">WORK_ZONE_TYPE</th>
<th data-quarto-table-cell-role="th">WZ_CLOSE_DETOUR</th>
<th data-quarto-table-cell-role="th">WZ_FLAGGER</th>
<th data-quarto-table-cell-role="th">WZ_LAW_OFFCR_IND</th>
<th data-quarto-table-cell-role="th">WZ_LN_CLOSURE</th>
<th data-quarto-table-cell-role="th">WZ_MOVING</th>
<th data-quarto-table-cell-role="th">WZ_OTHER</th>
<th data-quarto-table-cell-role="th">WZ_SHLDER_MDN</th>
<th data-quarto-table-cell-role="th">WZ_WORKERS_INJ_KILLED</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">691064</th>
<td>2025030047</td>
<td>NaN</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">691065</th>
<td>2025030596</td>
<td>NaN</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">691066</th>
<td>2025031303</td>
<td>NaN</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">691067</th>
<td>2025031608</td>
<td>NaN</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">691068</th>
<td>2025031769</td>
<td>NaN</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

<p>5 rows × 99 columns</p>
</div>
</div>
</div>
<div id="cell-15" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># return a random sample of rows</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>crash_data.sample(<span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">CRN</th>
<th data-quarto-table-cell-role="th">ARRIVAL_TM</th>
<th data-quarto-table-cell-role="th">AUTOMOBILE_COUNT</th>
<th data-quarto-table-cell-role="th">BELTED_DEATH_COUNT</th>
<th data-quarto-table-cell-role="th">BELTED_SUSP_SERIOUS_INJ_COUNT</th>
<th data-quarto-table-cell-role="th">BICYCLE_COUNT</th>
<th data-quarto-table-cell-role="th">BICYCLE_DEATH_COUNT</th>
<th data-quarto-table-cell-role="th">BICYCLE_SUSP_SERIOUS_INJ_COUNT</th>
<th data-quarto-table-cell-role="th">BUS_COUNT</th>
<th data-quarto-table-cell-role="th">CHLDPAS_DEATH_COUNT</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">WORK_ZONE_LOC</th>
<th data-quarto-table-cell-role="th">WORK_ZONE_TYPE</th>
<th data-quarto-table-cell-role="th">WZ_CLOSE_DETOUR</th>
<th data-quarto-table-cell-role="th">WZ_FLAGGER</th>
<th data-quarto-table-cell-role="th">WZ_LAW_OFFCR_IND</th>
<th data-quarto-table-cell-role="th">WZ_LN_CLOSURE</th>
<th data-quarto-table-cell-role="th">WZ_MOVING</th>
<th data-quarto-table-cell-role="th">WZ_OTHER</th>
<th data-quarto-table-cell-role="th">WZ_SHLDER_MDN</th>
<th data-quarto-table-cell-role="th">WZ_WORKERS_INJ_KILLED</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">275773</th>
<td>2012102585</td>
<td>NaN</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">62336</th>
<td>2006109139</td>
<td>NaN</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">235653</th>
<td>2011080277</td>
<td>NaN</td>
<td>3</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">318998</th>
<td>2013134287</td>
<td>NaN</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">127776</th>
<td>2008077372</td>
<td>NaN</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">180308</th>
<td>2009133334</td>
<td>NaN</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">301728</th>
<td>2013067991</td>
<td>930.0</td>
<td>3</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">667421</th>
<td>2024028660</td>
<td>1030.0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">654674</th>
<td>2023101670</td>
<td>1619.0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">533111</th>
<td>2019128325</td>
<td>NaN</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

<p>10 rows × 99 columns</p>
</div>
</div>
</div>
<ul>
<li>The <code>head</code> and <code>tail</code> functions can also take an argument for the number of rows to return.</li>
</ul>
<div id="cell-17" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># show the first 20 rows</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>crash_data.head(<span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">CRN</th>
<th data-quarto-table-cell-role="th">ARRIVAL_TM</th>
<th data-quarto-table-cell-role="th">AUTOMOBILE_COUNT</th>
<th data-quarto-table-cell-role="th">BELTED_DEATH_COUNT</th>
<th data-quarto-table-cell-role="th">BELTED_SUSP_SERIOUS_INJ_COUNT</th>
<th data-quarto-table-cell-role="th">BICYCLE_COUNT</th>
<th data-quarto-table-cell-role="th">BICYCLE_DEATH_COUNT</th>
<th data-quarto-table-cell-role="th">BICYCLE_SUSP_SERIOUS_INJ_COUNT</th>
<th data-quarto-table-cell-role="th">BUS_COUNT</th>
<th data-quarto-table-cell-role="th">CHLDPAS_DEATH_COUNT</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">WORK_ZONE_LOC</th>
<th data-quarto-table-cell-role="th">WORK_ZONE_TYPE</th>
<th data-quarto-table-cell-role="th">WZ_CLOSE_DETOUR</th>
<th data-quarto-table-cell-role="th">WZ_FLAGGER</th>
<th data-quarto-table-cell-role="th">WZ_LAW_OFFCR_IND</th>
<th data-quarto-table-cell-role="th">WZ_LN_CLOSURE</th>
<th data-quarto-table-cell-role="th">WZ_MOVING</th>
<th data-quarto-table-cell-role="th">WZ_OTHER</th>
<th data-quarto-table-cell-role="th">WZ_SHLDER_MDN</th>
<th data-quarto-table-cell-role="th">WZ_WORKERS_INJ_KILLED</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>2005000003</td>
<td>NaN</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>2005000044</td>
<td>NaN</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>2005000073</td>
<td>NaN</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>2005001018</td>
<td>NaN</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>2005001021</td>
<td>NaN</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>2005001022</td>
<td>NaN</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>2005001051</td>
<td>NaN</td>
<td>3</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>4.0</td>
<td>1.0</td>
<td>NaN</td>
<td>NaN</td>
<td>N</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>2005001066</td>
<td>NaN</td>
<td>3</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>2005001552</td>
<td>NaN</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>2005001782</td>
<td>NaN</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>2005002044</td>
<td>NaN</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>2005002045</td>
<td>NaN</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>2005002108</td>
<td>NaN</td>
<td>3</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>2005002335</td>
<td>NaN</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>2005002407</td>
<td>NaN</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">15</th>
<td>2005002411</td>
<td>NaN</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">16</th>
<td>2005002743</td>
<td>NaN</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">17</th>
<td>2005002822</td>
<td>NaN</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">18</th>
<td>2005003022</td>
<td>NaN</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">19</th>
<td>2005003031</td>
<td>NaN</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

<p>20 rows × 99 columns</p>
</div>
</div>
</div>
<ul>
<li>We can also select a subset of columns by using column indexing and a list of column names</li>
</ul>
<div id="cell-19" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>crash_data[[<span class="st">'MUNICIPALITY'</span>,<span class="st">'COUNTY'</span>, <span class="st">'DISTRICT'</span>]].sample(<span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">MUNICIPALITY</th>
<th data-quarto-table-cell-role="th">COUNTY</th>
<th data-quarto-table-cell-role="th">DISTRICT</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">609505</th>
<td>15208</td>
<td>15</td>
<td>6</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">470681</th>
<td>23103</td>
<td>23</td>
<td>6</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">410873</th>
<td>67301</td>
<td>67</td>
<td>6</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">595258</th>
<td>15247</td>
<td>15</td>
<td>6</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">595418</th>
<td>67301</td>
<td>67</td>
<td>6</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">312409</th>
<td>15301</td>
<td>15</td>
<td>6</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">689142</th>
<td>46216</td>
<td>46</td>
<td>6</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">180613</th>
<td>23424</td>
<td>23</td>
<td>6</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">150335</th>
<td>9204</td>
<td>9</td>
<td>6</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">224956</th>
<td>23202</td>
<td>23</td>
<td>6</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">362013</th>
<td>46225</td>
<td>46</td>
<td>6</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">49881</th>
<td>9215</td>
<td>9</td>
<td>6</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">636823</th>
<td>67301</td>
<td>67</td>
<td>6</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">94714</th>
<td>46209</td>
<td>46</td>
<td>6</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">135188</th>
<td>67301</td>
<td>67</td>
<td>6</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">550738</th>
<td>46113</td>
<td>46</td>
<td>6</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">664495</th>
<td>67301</td>
<td>67</td>
<td>6</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">92922</th>
<td>67301</td>
<td>67</td>
<td>6</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">318708</th>
<td>9215</td>
<td>9</td>
<td>6</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">500178</th>
<td>46102</td>
<td>46</td>
<td>6</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>

<section id="key-point-1" class="level4">
<h4 data-anchor-id="key-point-1"><em>Key point</em></h4>
<ul>
<li><p>The point is not so much the specific syntax and function you use but the importance of <code>eyeballing</code> the data to get a sense of what the various features/fields or variables contain.</p></li>
<li><p>For instance:</p>
<ul>
<li>The <code>MUNICIPALITY</code>, <code>COUNTY</code> and <code>DISTRICT</code> fields are numbers and not names as one might expect. So there must be a cross reference table somewhere that indicates the name of the district with code <code>6</code>, etc.</li>
<li><code>TIME_OF_DAY</code> is an integer, e.g.&nbsp;<code>1515</code>, <code>0</code>, <code>742</code>, which we would initially assume is in 24 hour clock and relates to <code>3:15pm</code>,<code>12:00am</code> and <code>7:42am</code> respectively. Although a value of <code>0</code> might also be used to indicate an unknown time.</li>
<li><code>DAY_OF_WEEK</code> is also a number. So must question whether <code>1</code> means Monday or Sunday.</li>
</ul></li>
</ul>
</section>
<section id="list-column-names" class="level4">
<h4 data-anchor-id="list-column-names">List column names</h4>
<ul>
<li>The <code>.columns</code> attribute of a pandas <code>DataFrame</code> is a list of the column names. Taken here from the first row of the CSV file.</li>
</ul>
<div id="cell-22" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>crash_data.columns</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>Index(['CRN', 'ARRIVAL_TM', 'AUTOMOBILE_COUNT', 'BELTED_DEATH_COUNT',
       'BELTED_SUSP_SERIOUS_INJ_COUNT', 'BICYCLE_COUNT', 'BICYCLE_DEATH_COUNT',
       'BICYCLE_SUSP_SERIOUS_INJ_COUNT', 'BUS_COUNT', 'CHLDPAS_DEATH_COUNT',
       'CHLDPAS_SUSP_SERIOUS_INJ_COUNT', 'COLLISION_TYPE', 'COMM_VEH_COUNT',
       'CONS_ZONE_SPD_LIM', 'COUNTY', 'CRASH_MONTH', 'CRASH_YEAR',
       'DAY_OF_WEEK', 'DEC_LATITUDE', 'DEC_LONGITUDE', 'DISPATCH_TM',
       'DISTRICT', 'DRIVER_COUNT_16YR', 'DRIVER_COUNT_17YR',
       'DRIVER_COUNT_18YR', 'DRIVER_COUNT_19YR', 'DRIVER_COUNT_20YR',
       'DRIVER_COUNT_50_64YR', 'DRIVER_COUNT_65_74YR', 'DRIVER_COUNT_75PLUS',
       'EST_HRS_CLOSED', 'FATAL_COUNT', 'HEAVY_TRUCK_COUNT',
       'HORSE_BUGGY_COUNT', 'HOUR_OF_DAY', 'ILLUMINATION', 'INJURY_COUNT',
       'INTERSECTION_RELATED', 'INTERSECT_TYPE', 'LANE_CLOSED', 'LATITUDE',
       'LN_CLOSE_DIR', 'LOCATION_TYPE', 'LONGITUDE', 'MAX_SEVERITY_LEVEL',
       'MCYCLE_DEATH_COUNT', 'MCYCLE_SUSP_SERIOUS_INJ_COUNT',
       'MOTORCYCLE_COUNT', 'MUNICIPALITY', 'NONMOTR_COUNT',
       'NONMOTR_DEATH_COUNT', 'NONMOTR_SUSP_SERIOUS_INJ_COUNT',
       'NTFY_HIWY_MAINT', 'PED_COUNT', 'PED_DEATH_COUNT',
       'PED_SUSP_SERIOUS_INJ_COUNT', 'PERSON_COUNT', 'POLICE_AGCY',
       'POSSIBLE_INJ_COUNT', 'RDWY_SURF_TYPE_CD', 'RELATION_TO_ROAD',
       'ROADWAY_CLEARED', 'ROAD_CONDITION', 'SCH_BUS_IND', 'SCH_ZONE_IND',
       'SECONDARY_CRASH', 'SMALL_TRUCK_COUNT', 'SPEC_JURIS_CD',
       'SUSP_MINOR_INJ_COUNT', 'SUSP_SERIOUS_INJ_COUNT', 'SUV_COUNT',
       'TCD_FUNC_CD', 'TCD_TYPE', 'TFC_DETOUR_IND', 'TIME_OF_DAY',
       'TOTAL_UNITS', 'TOT_INJ_COUNT', 'UNBELTED_OCC_COUNT', 'UNB_DEATH_COUNT',
       'UNB_SUSP_SERIOUS_INJ_COUNT', 'UNK_INJ_DEG_COUNT', 'UNK_INJ_PER_COUNT',
       'URBAN_RURAL', 'VAN_COUNT', 'VEHICLE_COUNT', 'WEATHER1', 'WEATHER2',
       'WORKERS_PRES', 'WORK_ZONE_IND', 'WORK_ZONE_LOC', 'WORK_ZONE_TYPE',
       'WZ_CLOSE_DETOUR', 'WZ_FLAGGER', 'WZ_LAW_OFFCR_IND', 'WZ_LN_CLOSURE',
       'WZ_MOVING', 'WZ_OTHER', 'WZ_SHLDER_MDN', 'WZ_WORKERS_INJ_KILLED'],
      dtype='str')</code></pre>
</div>
</div>
</section>
<section id="notice" class="level4">
<h4 data-anchor-id="notice">Notice…</h4>
<ul>
<li>Some of these names are more clear than others:
<ul>
<li><code>MUNICIPALITY</code>, <code>CRASH_YEAR</code>, <code>CRASH_MONTH</code>, <code>DAY_OF_WEEK</code>, <code>TIME_OF_DAY</code>, <code>HOUR_OF_DAY</code>, all appear relatively self-explanatory</li>
<li>but what does <code>CRN</code> field mean?</li>
</ul></li>
<li>There are groups of related columns, e.g.
<ul>
<li><p><code>DRIVER_COUNT_</code> is broken down into age bands instead of a single numeric column:</p>
<ul>
<li><code>DRIVER_COUNT_16yr</code></li>
<li><code>DRIVER_COUNT_17yr</code></li>
<li><code>DRIVER_COUNT_18yr</code></li>
<li><code>DRIVER_COUNT_19yr</code></li>
<li><code>DRIVER_COUNT_20yr</code></li>
<li><code>DRIVER_COUNT_50_64yr</code></li>
<li><code>DRIVER_COUNT_65_74yr</code></li>
<li><code>DRIVER_COUNT_75plus</code></li>
</ul>
<p>but not continuous or equal ones. What does this suggest?</p></li>
<li><p>Injury types are broken down into categories</p>
<ul>
<li><code>BELTED_SUSP_SERIOUS_INJ_COUNT</code></li>
<li><code>BICYCLE_SUSP_SERIOUS_INJ_COUNT</code></li>
<li><code>CHLDPAS_SUSP_SERIOUS_INJ_COUNT</code></li>
<li><code>MCYCLE_SUSP_SERIOUS_INJ_COUNT</code></li>
<li><code>NONMOTR_SUSP_SERIOUS_INJ_COUNT</code></li>
<li><code>PED_SUSP_SERIOUS_INJ_COUNT</code></li>
<li><code>POSSIBLE_INJ_COUNT</code></li>
<li><code>SUSP_MINOR_INJ_COUNT</code></li>
<li><code>SUSP_SERIOUS_INJ_COUNT</code></li>
<li><code>TOT_INJ_COUNT</code></li>
<li><code>UNB_SUSP_SERIOUS_INJ_COUNT</code></li>
<li><code>UNK_INJ_DEG_COUNT</code></li>
<li><code>UNK_INJ_PER_COUNT</code></li>
<li><code>WZ_WORKERS_INJ_KILLED</code></li>
</ul>
<p><br><br></p></li>
</ul></li>
<li>It is easier to look at these column names in alphabetical order to get a sense of what is recorded in the data about each crash incident.</li>
</ul>
<div id="cell-24" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>crash_data.columns.sort_values()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>Index(['ARRIVAL_TM', 'AUTOMOBILE_COUNT', 'BELTED_DEATH_COUNT',
       'BELTED_SUSP_SERIOUS_INJ_COUNT', 'BICYCLE_COUNT', 'BICYCLE_DEATH_COUNT',
       'BICYCLE_SUSP_SERIOUS_INJ_COUNT', 'BUS_COUNT', 'CHLDPAS_DEATH_COUNT',
       'CHLDPAS_SUSP_SERIOUS_INJ_COUNT', 'COLLISION_TYPE', 'COMM_VEH_COUNT',
       'CONS_ZONE_SPD_LIM', 'COUNTY', 'CRASH_MONTH', 'CRASH_YEAR', 'CRN',
       'DAY_OF_WEEK', 'DEC_LATITUDE', 'DEC_LONGITUDE', 'DISPATCH_TM',
       'DISTRICT', 'DRIVER_COUNT_16YR', 'DRIVER_COUNT_17YR',
       'DRIVER_COUNT_18YR', 'DRIVER_COUNT_19YR', 'DRIVER_COUNT_20YR',
       'DRIVER_COUNT_50_64YR', 'DRIVER_COUNT_65_74YR', 'DRIVER_COUNT_75PLUS',
       'EST_HRS_CLOSED', 'FATAL_COUNT', 'HEAVY_TRUCK_COUNT',
       'HORSE_BUGGY_COUNT', 'HOUR_OF_DAY', 'ILLUMINATION', 'INJURY_COUNT',
       'INTERSECTION_RELATED', 'INTERSECT_TYPE', 'LANE_CLOSED', 'LATITUDE',
       'LN_CLOSE_DIR', 'LOCATION_TYPE', 'LONGITUDE', 'MAX_SEVERITY_LEVEL',
       'MCYCLE_DEATH_COUNT', 'MCYCLE_SUSP_SERIOUS_INJ_COUNT',
       'MOTORCYCLE_COUNT', 'MUNICIPALITY', 'NONMOTR_COUNT',
       'NONMOTR_DEATH_COUNT', 'NONMOTR_SUSP_SERIOUS_INJ_COUNT',
       'NTFY_HIWY_MAINT', 'PED_COUNT', 'PED_DEATH_COUNT',
       'PED_SUSP_SERIOUS_INJ_COUNT', 'PERSON_COUNT', 'POLICE_AGCY',
       'POSSIBLE_INJ_COUNT', 'RDWY_SURF_TYPE_CD', 'RELATION_TO_ROAD',
       'ROADWAY_CLEARED', 'ROAD_CONDITION', 'SCH_BUS_IND', 'SCH_ZONE_IND',
       'SECONDARY_CRASH', 'SMALL_TRUCK_COUNT', 'SPEC_JURIS_CD',
       'SUSP_MINOR_INJ_COUNT', 'SUSP_SERIOUS_INJ_COUNT', 'SUV_COUNT',
       'TCD_FUNC_CD', 'TCD_TYPE', 'TFC_DETOUR_IND', 'TIME_OF_DAY',
       'TOTAL_UNITS', 'TOT_INJ_COUNT', 'UNBELTED_OCC_COUNT', 'UNB_DEATH_COUNT',
       'UNB_SUSP_SERIOUS_INJ_COUNT', 'UNK_INJ_DEG_COUNT', 'UNK_INJ_PER_COUNT',
       'URBAN_RURAL', 'VAN_COUNT', 'VEHICLE_COUNT', 'WEATHER1', 'WEATHER2',
       'WORKERS_PRES', 'WORK_ZONE_IND', 'WORK_ZONE_LOC', 'WORK_ZONE_TYPE',
       'WZ_CLOSE_DETOUR', 'WZ_FLAGGER', 'WZ_LAW_OFFCR_IND', 'WZ_LN_CLOSURE',
       'WZ_MOVING', 'WZ_OTHER', 'WZ_SHLDER_MDN', 'WZ_WORKERS_INJ_KILLED'],
      dtype='str')</code></pre>
</div>
</div>
</section>

<section id="looking-at-the-data-dictionarycode-book" class="level3">
<h3 data-anchor-id="looking-at-the-data-dictionarycode-book">3. Looking at the data dictionary/code book</h3>
<ul>
<li><p>Most datasets that have been made publicly available should have an accompanying code book or data dictionary to describe what each of the fields mean. How they were collected. What units they are measured in. What data type has been used to record them (e.g.&nbsp;text vs number vs date).</p></li>
<li><p>For this dataset there are a couple of versions:</p>
<ul>
<li>The Metadata reources on phila.gov site:
<ul>
<li>https://metadata.phila.gov/index.html#home/?view_280_search=crash&amp;view_280_page=1</li>
<li>You can see there have been a number of different subsets of the data released over the years:
<ul>
<li>https://metadata.phila.gov/index.html#home/datasetdetails/5543865420583086178c4eba/</li>
</ul></li>
</ul></li>
<li>The PennDot data dictionary linked from this page:
<ul>
<li>https://experience.arcgis.com/experience/51809b06e7b140208a4ed6fbad964990/page/District#data_s=id%3AdataSource_1-196447a967d-layer-68%3A321</li>
<li>Data Dictionary - https://gis.penndot.pa.gov/gishub/crashZip/Crash_Data_Dictionary_2025.pdf</li>
<li><a href="Crash_Data_Dictionary_2025.pdf">That PDF file</a> is in this folder and you should make sure to review it.</li>
</ul></li>
</ul></li>
<li><p>We’ve extracted the key information and put it into a CSV file, which means we can load it into a Pandas dataframe.</p></li>
</ul>
<div id="cell-26" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>data_dictionary <span class="op">=</span> pd.read_csv(<span class="st">'data/data_dictionary.csv'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="cell-27" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>data_dictionary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Column_Name</th>
<th data-quarto-table-cell-role="th">Description</th>
<th data-quarto-table-cell-role="th">Type</th>
<th data-quarto-table-cell-role="th">Length</th>
<th data-quarto-table-cell-role="th">Constraints</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>ARRIVAL_TM</td>
<td>Time police arrived at the scene</td>
<td>TEXT</td>
<td>4.0</td>
<td>HHMM</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>AUTOMOBILE_COUNT</td>
<td>Total amount of Automobiles Involved</td>
<td>NUMBER</td>
<td>2.0</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>BELTED_DEATH_COUNT</td>
<td>Total Deaths of belted occupants</td>
<td>NUMBER</td>
<td>2.0</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>BELTED_SUSP_SERIOUS_INJ_COUNT</td>
<td>Total Suspected Serious Injuries of belted occ...</td>
<td>NUMBER</td>
<td>2.0</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>BICYCLE_COUNT</td>
<td>Total amount of Bicycles involved</td>
<td>NUMBER</td>
<td>2.0</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">...</th>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">94</th>
<td>WZ_LN_CLOSURE</td>
<td>Did Work zone have a lane closure?</td>
<td>TEXT</td>
<td>1.0</td>
<td>1=Y, 0 = N</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">95</th>
<td>WZ_MOVING</td>
<td>Was there moving work in the zone?</td>
<td>TEXT</td>
<td>1.0</td>
<td>1=Y, 0 = N</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">96</th>
<td>WZ_OTHER</td>
<td>Was this a special type of work zone?</td>
<td>TEXT</td>
<td>1.0</td>
<td>1=Y, 0 = N</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">97</th>
<td>WZ_SHLDER_MDN</td>
<td>Was a median/shoulder in the zone?</td>
<td>TEXT</td>
<td>1.0</td>
<td>1=Y, 0 = N</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">98</th>
<td>WZ_WORKERS_INJ_KILLED</td>
<td>Were any Work Zone workers injured or\rkilled ...</td>
<td>TEXT</td>
<td>1.0</td>
<td>1=Y, 0 = N</td>
</tr>
</tbody>
</table>

<p>99 rows × 5 columns</p>
</div>
</div>
</div>
<ul>
<li>This tells us that the <code>crn</code> field is actually the <code>Crash Record Number</code>:</li>
</ul>
<div id="cell-29" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>data_dictionary.set_index(<span class="st">'Column_Name'</span>).loc[<span class="st">'CRN'</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>Description                                  Crash Record Number
Type                                                      NUMBER
Length                                                       2.0
Constraints    Database key field that\ridentifies a unique c...
Name: CRN, dtype: object</code></pre>
</div>
</div>
</section>
<section id="describing-the-data" class="level3">
<h3 data-anchor-id="describing-the-data">4. Describing the data</h3>
<ul>
<li><p>The next step is to start to look at the values and distributions in various columns/fields</p></li>
<li><p>We can select a specific column or sets of columns using <strong>INDEXING</strong>. There are various ways to do this in a Pandas <code>DataFrame</code>. Most often it is clearest to use the column name.</p></li>
</ul>
<div id="cell-31" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>data_dictionary.set_index(<span class="st">'Column_Name'</span>).loc[<span class="st">'FATAL_COUNT'</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<pre><code>Description    Total amount of fatalities involved
Type                                        NUMBER
Length                                         2.0
Constraints                                    NaN
Name: FATAL_COUNT, dtype: object</code></pre>
</div>
</div>
<div id="cell-32" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>crash_data[<span class="st">'FATAL_COUNT'</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>0         0
1         0
2         0
3         1
4         0
         ..
691064    0
691065    0
691066    0
691067    0
691068    0
Name: FATAL_COUNT, Length: 691069, dtype: int64</code></pre>
</div>
</div>
<ul>
<li>We might immediately be tempted to try and visualize this distribution with some kind of plot. And Pandas includes some nice easy ways to do this that we will learn about.</li>
</ul>
<div id="cell-34" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>crash_data[<span class="st">'FATAL_COUNT'</span>].plot()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_Exploring_PDOT_Crash_Data_files/figure-html/cell-17-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<section id="but" class="level4">
<h4 data-anchor-id="but">BUT!</h4>
<ul>
<li><p>We should also stop and think about what we are looking for and what story or stories we anticipate in the values before diving straight into charts and graphs. Here Python is attemping to plot each of the 77462 rows in the data frame along the x-axis with the height on the y-axis representing the number of fatalities.</p></li>
<li><p>This plot isn’t particularly enlightening or clear. The resolution of this plot makes it seem like the majority of incidents had at least one fatality. This misleading because as we see below less than 1% of crash incidents resulted in a fatality. If we stretch the plot on the x-axis (by changing the aspect ration of the plot) it becomes a little clearer that the points with a value of <code>1</code> are more sparse than it at first appeared.</p></li>
</ul>
<div id="cell-36" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>crash_data[<span class="st">'FATAL_COUNT'</span>].plot(figsize<span class="op">=</span>(<span class="dv">20</span>,<span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_Exploring_PDOT_Crash_Data_files/figure-html/cell-18-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Even with this change, the plot gives the wrong impression of the proportion of incidents involving a fatality.</p></li>
<li><p>Having said that, it can be warranted to try and visualize every instance (all the rows) like this. And sometimes a picture will give you insight that it difficult to get from a table.</p></li>
<li><p>Here we can see that most crashes fortunately did not include fatalities. And that only a two in a 10 year period resulted in 4 deaths in a single crash.</p></li>
<li><p>And compare the plot with this simple table, which tallies the number of rows that contain each number of fatalities.</p></li>
</ul>
<div id="cell-38" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>crash_data[<span class="st">'FATAL_COUNT'</span>].value_counts()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="18">
<pre><code>FATAL_COUNT
0    685996
1      4825
2       207
3        33
4         8
Name: count, dtype: int64</code></pre>
</div>
</div>
<p>The <code>.value_counts()</code> function applied to a column provides a tally of the number of rows that have each of the range of existing values for the column.</p>
<p>Here we see five possible values for the number of fatalites: 0, 1, 2, 3 or 4 and the number of times each value occurs in a row in the data.</p>
<p>We might also want to see these counts expressed as proportions of the total number of rows:</p>
<div id="cell-40" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>crash_data[<span class="st">'FATAL_COUNT'</span>].value_counts(normalize<span class="op">=</span><span class="va">True</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="19">
<pre><code>FATAL_COUNT
0    0.992659
1    0.006982
2    0.000300
3    0.000048
4    0.000012
Name: proportion, dtype: float64</code></pre>
</div>
</div>
<ul>
<li><p>We will learn about a number of other ways to summarize the values in a column of a data frame.</p></li>
<li><p>Where the values are interval or continuous numbers the <code>.describe()</code> function gives a standard statistical summary.</p></li>
</ul>
<div id="cell-42" class="cell" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>crash_data[<span class="st">'FATAL_COUNT'</span>].describe()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="20">
<pre><code>count    691069.000000
mean          0.007771
std           0.093460
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           4.000000
Name: FATAL_COUNT, dtype: float64</code></pre>
</div>
</div>
<ul>
<li><p>We will also spend time looking a <strong>DATA TYPES</strong> where they are relevant and might affect our data analysis.</p></li>
<li><p>For instance, the <code>CRASH_YEAR</code> field gets treated by Pandas as an <em>integer</em> (i.e.&nbsp;whole number) field.</p></li>
</ul>
<div id="cell-44" class="cell" data-execution_count="21">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>crash_data[<span class="st">'CRASH_YEAR'</span>].head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<pre><code>0    2005
1    2005
2    2005
3    2005
4    2005
Name: CRASH_YEAR, dtype: int64</code></pre>
</div>
</div>
<ul>
<li>So while the <code>.value_counts()</code> function will gives us a useful summary:</li>
</ul>
<div id="cell-46" class="cell" data-execution_count="22">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>crash_data[<span class="st">'CRASH_YEAR'</span>].value_counts()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<pre><code>CRASH_YEAR
2005    38099
2006    37759
2007    37603
2016    37090
2018    36327
2017    36218
2019    36044
2015    35934
2008    34801
2011    34709
2012    34695
2013    34578
2009    34418
2010    34141
2014    33834
2021    33236
2022    31753
2023    30416
2020    29751
2024    29663
Name: count, dtype: int64</code></pre>
</div>
</div>
<ul>
<li>If we use the <code>.describe()</code> method then we’ll get some strange results</li>
</ul>
<div id="cell-48" class="cell" data-execution_count="23">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>crash_data[<span class="st">'CRASH_YEAR'</span>].describe()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<pre><code>count    691069.000000
mean       2014.211430
std           5.720413
min        2005.000000
25%        2009.000000
50%        2014.000000
75%        2019.000000
max        2024.000000
Name: CRASH_YEAR, dtype: float64</code></pre>
</div>
</div>
<ul>
<li><p>The <em>mean</em> or average year in the dataset is <code>2014.211430</code> - which makes little sense at all!</p></li>
<li><p>We want to check the range of years involved - from <code>min</code> and <code>max</code> we see <code>2005</code> and <code>2024</code> &gt; Don’t always trust filenames or descriptions. <strong>CHECK THE DATA YOURSELF</strong>.</p></li>
<li><p>We need to tell Pandas to treat the year values as <em>categories</em>.</p></li>
</ul>
<div id="cell-50" class="cell" data-execution_count="24">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>crash_data[<span class="st">'CRASH_YEAR'</span>].astype(<span class="st">'category'</span>).head(<span class="dv">15</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="24">
<pre><code>0     2005
1     2005
2     2005
3     2005
4     2005
5     2005
6     2005
7     2005
8     2005
9     2005
10    2005
11    2005
12    2005
13    2005
14    2005
Name: CRASH_YEAR, dtype: category
Categories (20, int64): [2005, 2006, 2007, 2008, ..., 2021, 2022, 2023, 2024]</code></pre>
</div>
</div>
<ul>
<li>And now the results of using <code>.describe()</code> are more sensible and useful.</li>
</ul>
<div id="cell-52" class="cell" data-execution_count="25">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>crash_data[<span class="st">'CRASH_YEAR'</span>].astype(<span class="st">'category'</span>).describe()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="25">
<pre><code>count     691069
unique        20
top         2005
freq       38099
Name: CRASH_YEAR, dtype: int64</code></pre>
</div>
</div>
<ul>
<li>We get a more appropriate summary of the <code>CRASH_YEAR</code> variable as <strong>CATEGORICAL</strong>
<ul>
<li>There are 20 different values (years recorded in the dataset)</li>
</ul></li>
</ul>
</section>
</section>
<section id="grouping-and-aggregating-the-data" class="level3">
<h3 data-anchor-id="grouping-and-aggregating-the-data">5. Grouping and aggregating the data</h3>
<ul>
<li><p>The next step is often to group and subset a dataset according to certain fields, such as <code>CRASH_YEAR</code>.</p></li>
<li><p>Again Pandas gives us different ways to do this that we learn about.</p></li>
<li><p>The <code>.groupby(FIELD)</code> function will split a single <code>DataFrame</code> into a number of different ones based on the values of the grouping field or fields.</p>
<ul>
<li>Here we cam see the shape of each of the resulting dataframes by <code>CRASH_YEAR</code></li>
</ul></li>
</ul>
<div id="cell-55" class="cell" data-execution_count="26">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> year, ydf <span class="kw">in</span> crash_data.groupby(<span class="st">'CRASH_YEAR'</span>):</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(year, ydf.shape)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>2005 (38099, 99)
2006 (37759, 99)
2007 (37603, 99)
2008 (34801, 99)
2009 (34418, 99)
2010 (34141, 99)
2011 (34709, 99)
2012 (34695, 99)
2013 (34578, 99)
2014 (33834, 99)
2015 (35934, 99)
2016 (37090, 99)
2017 (36218, 99)
2018 (36327, 99)
2019 (36044, 99)
2020 (29751, 99)
2021 (33236, 99)
2022 (31753, 99)
2023 (30416, 99)
2024 (29663, 99)</code></pre>
</div>
</div>
<div id="cell-56" class="cell" data-execution_count="27">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>crash_data.groupby(<span class="st">'CRASH_YEAR'</span>)[<span class="st">'CRN'</span>].count().plot(kind<span class="op">=</span><span class="st">'bar'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_Exploring_PDOT_Crash_Data_files/figure-html/cell-28-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>So we seem to have a relatively even number of crash events in each year. That is, there are no spikes or troughs and no clear increasing or describe trends.</p></li>
<li><p>We could calculate the average number of crash events per year from 2005 to 2024:</p></li>
</ul>
<div id="cell-58" class="cell" data-execution_count="28">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>avg_crash_per_year<span class="op">=</span>crash_data.groupby(<span class="st">'CRASH_YEAR'</span>).size().mean()</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>avg_crash_per_year</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="28">
<pre><code>np.float64(34553.45)</code></pre>
</div>
</div>
<ul>
<li><p>So on average across the period 2005 to 2024 there were 34553.45 crash incidents recorded each year.</p></li>
<li><p>There will be some variability year by year and we could explore that with another version of the bar plot where bars are colored purple if there were less incidents than the average and green if there were more during each year.</p></li>
</ul>
<div id="cell-60" class="cell" data-execution_count="29">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>above_mean<span class="op">=</span>np.where(crash_data.groupby(<span class="st">'CRASH_YEAR'</span>).size()<span class="op">&gt;</span>avg_crash_per_year, <span class="st">'green'</span>, <span class="st">'purple'</span>)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>crash_data.groupby(<span class="st">'CRASH_YEAR'</span>).size().plot(kind<span class="op">=</span><span class="st">'bar'</span>, color<span class="op">=</span>above_mean)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>plt.hlines(y<span class="op">=</span>avg_crash_per_year, xmin<span class="op">=</span><span class="dv">0</span>, xmax<span class="op">=</span><span class="dv">20</span>, linestyle<span class="op">=</span><span class="st">'dotted'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_Exploring_PDOT_Crash_Data_files/figure-html/cell-30-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>So there were a lower number of incidents than average in 2011, 2014 and 2017. Note that for this kind of analysis and visualization</p></li>
<li><p>We can group by more than one field and then get a count of the number of rows in each combination of, for example, <code>CRASH_YEAR</code> and <code>CRASH_MONTH</code></p></li>
</ul>
<div id="cell-62" class="cell" data-execution_count="30">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>crash_data.groupby([<span class="st">'CRASH_YEAR'</span>,<span class="st">'CRASH_MONTH'</span>]).count()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="30">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">CRN</th>
<th data-quarto-table-cell-role="th">ARRIVAL_TM</th>
<th data-quarto-table-cell-role="th">AUTOMOBILE_COUNT</th>
<th data-quarto-table-cell-role="th">BELTED_DEATH_COUNT</th>
<th data-quarto-table-cell-role="th">BELTED_SUSP_SERIOUS_INJ_COUNT</th>
<th data-quarto-table-cell-role="th">BICYCLE_COUNT</th>
<th data-quarto-table-cell-role="th">BICYCLE_DEATH_COUNT</th>
<th data-quarto-table-cell-role="th">BICYCLE_SUSP_SERIOUS_INJ_COUNT</th>
<th data-quarto-table-cell-role="th">BUS_COUNT</th>
<th data-quarto-table-cell-role="th">CHLDPAS_DEATH_COUNT</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">WORK_ZONE_LOC</th>
<th data-quarto-table-cell-role="th">WORK_ZONE_TYPE</th>
<th data-quarto-table-cell-role="th">WZ_CLOSE_DETOUR</th>
<th data-quarto-table-cell-role="th">WZ_FLAGGER</th>
<th data-quarto-table-cell-role="th">WZ_LAW_OFFCR_IND</th>
<th data-quarto-table-cell-role="th">WZ_LN_CLOSURE</th>
<th data-quarto-table-cell-role="th">WZ_MOVING</th>
<th data-quarto-table-cell-role="th">WZ_OTHER</th>
<th data-quarto-table-cell-role="th">WZ_SHLDER_MDN</th>
<th data-quarto-table-cell-role="th">WZ_WORKERS_INJ_KILLED</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">CRASH_YEAR</th>
<th data-quarto-table-cell-role="th">CRASH_MONTH</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th rowspan="5" data-quarto-table-cell-role="th" data-valign="top">2005</th>
<th data-quarto-table-cell-role="th">1</th>
<td>3118</td>
<td>1</td>
<td>3118</td>
<td>3118</td>
<td>3118</td>
<td>3118</td>
<td>3118</td>
<td>3118</td>
<td>3118</td>
<td>3118</td>
<td>...</td>
<td>20</td>
<td>20</td>
<td>1</td>
<td>2</td>
<td>19</td>
<td>4</td>
<td>3</td>
<td>4</td>
<td>5</td>
<td>0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2</th>
<td>2865</td>
<td>1</td>
<td>2865</td>
<td>2865</td>
<td>2865</td>
<td>2865</td>
<td>2865</td>
<td>2865</td>
<td>2865</td>
<td>2865</td>
<td>...</td>
<td>26</td>
<td>26</td>
<td>0</td>
<td>3</td>
<td>26</td>
<td>7</td>
<td>0</td>
<td>2</td>
<td>4</td>
<td>0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">3</th>
<td>2814</td>
<td>4</td>
<td>2814</td>
<td>2814</td>
<td>2814</td>
<td>2814</td>
<td>2814</td>
<td>2814</td>
<td>2814</td>
<td>2814</td>
<td>...</td>
<td>29</td>
<td>29</td>
<td>1</td>
<td>3</td>
<td>29</td>
<td>5</td>
<td>2</td>
<td>4</td>
<td>8</td>
<td>0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">4</th>
<td>3116</td>
<td>2</td>
<td>3116</td>
<td>3116</td>
<td>3116</td>
<td>3116</td>
<td>3116</td>
<td>3116</td>
<td>3116</td>
<td>3116</td>
<td>...</td>
<td>45</td>
<td>45</td>
<td>2</td>
<td>2</td>
<td>45</td>
<td>11</td>
<td>3</td>
<td>1</td>
<td>18</td>
<td>0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">5</th>
<td>3347</td>
<td>0</td>
<td>3347</td>
<td>3347</td>
<td>3347</td>
<td>3347</td>
<td>3347</td>
<td>3347</td>
<td>3347</td>
<td>3347</td>
<td>...</td>
<td>49</td>
<td>49</td>
<td>3</td>
<td>5</td>
<td>49</td>
<td>12</td>
<td>3</td>
<td>3</td>
<td>9</td>
<td>0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">...</th>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<th rowspan="5" data-quarto-table-cell-role="th" data-valign="top">2024</th>
<th data-quarto-table-cell-role="th">8</th>
<td>2292</td>
<td>1918</td>
<td>2292</td>
<td>2292</td>
<td>2292</td>
<td>2292</td>
<td>2292</td>
<td>2292</td>
<td>2292</td>
<td>2292</td>
<td>...</td>
<td>29</td>
<td>29</td>
<td>20</td>
<td>20</td>
<td>29</td>
<td>23</td>
<td>19</td>
<td>19</td>
<td>21</td>
<td>29</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>2322</td>
<td>421</td>
<td>2322</td>
<td>2322</td>
<td>2322</td>
<td>2322</td>
<td>2322</td>
<td>2322</td>
<td>2322</td>
<td>2322</td>
<td>...</td>
<td>19</td>
<td>19</td>
<td>11</td>
<td>11</td>
<td>19</td>
<td>14</td>
<td>11</td>
<td>12</td>
<td>15</td>
<td>19</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>2831</td>
<td>879</td>
<td>2831</td>
<td>2831</td>
<td>2831</td>
<td>2831</td>
<td>2831</td>
<td>2831</td>
<td>2831</td>
<td>2831</td>
<td>...</td>
<td>26</td>
<td>26</td>
<td>15</td>
<td>14</td>
<td>26</td>
<td>16</td>
<td>15</td>
<td>16</td>
<td>21</td>
<td>26</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>2684</td>
<td>822</td>
<td>2684</td>
<td>2684</td>
<td>2684</td>
<td>2684</td>
<td>2684</td>
<td>2684</td>
<td>2684</td>
<td>2684</td>
<td>...</td>
<td>15</td>
<td>15</td>
<td>7</td>
<td>7</td>
<td>15</td>
<td>10</td>
<td>8</td>
<td>8</td>
<td>12</td>
<td>15</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>2722</td>
<td>1061</td>
<td>2722</td>
<td>2722</td>
<td>2722</td>
<td>2722</td>
<td>2722</td>
<td>2722</td>
<td>2722</td>
<td>2722</td>
<td>...</td>
<td>17</td>
<td>17</td>
<td>8</td>
<td>7</td>
<td>17</td>
<td>11</td>
<td>8</td>
<td>8</td>
<td>12</td>
<td>17</td>
</tr>
</tbody>
</table>

<p>240 rows × 97 columns</p>
</div>
</div>
</div>
<ul>
<li><p>This is a little verbose as it shows these counts for all the columns.</p></li>
<li><p>We can select a single column or group of columns of interest and then sum up the numbers in them.</p></li>
<li><p>For example, here are the numbers of bicycles involved in crashes by year and month.</p></li>
</ul>
<div id="cell-64" class="cell" data-execution_count="31">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>crash_data.groupby([<span class="st">'CRASH_YEAR'</span>,<span class="st">'CRASH_MONTH'</span>])[<span class="st">'BICYCLE_COUNT'</span>].<span class="bu">sum</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="31">
<pre><code>CRASH_YEAR  CRASH_MONTH
2005        1              13
            2              12
            3              19
            4              63
            5              67
                           ..
2024        8               0
            9               0
            10              0
            11              0
            12              0
Name: BICYCLE_COUNT, Length: 240, dtype: int64</code></pre>
</div>
</div>
<ul>
<li>This really does lend itself to a visualization to help us look for trends and patterns.</li>
</ul>
<div id="cell-66" class="cell" data-execution_count="32">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">18</span>,<span class="dv">4</span>))</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>crash_data.groupby([<span class="st">'CRASH_YEAR'</span>,<span class="st">'CRASH_MONTH'</span>])[<span class="st">'BICYCLE_COUNT'</span>].<span class="bu">sum</span>().plot(kind<span class="op">=</span><span class="st">'bar'</span>)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>plt.suptitle(<span class="st">'Seasonal trends in the number of crashes with bicycles involved'</span>, </span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>             fontsize<span class="op">=</span><span class="dv">20</span>, y<span class="op">=</span><span class="fl">1.02</span>)</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'(In Philadelphia city region 2005-2024)'</span>, fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_Exploring_PDOT_Crash_Data_files/figure-html/cell-33-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Look carefully at the axes in any plot you create.
<ul>
<li>Here each point on the x-axis represents a month particular year, e.g.&nbsp;<code>2011,1</code> means January 2011 and <code>2013,4</code> means March 2013.</li>
<li>The y-axis shows the number of incidents and starts from zero.</li>
</ul></li>
</ul>
<div id="cell-68" class="cell" data-execution_count="33">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>crash_data.groupby([<span class="st">'CRASH_YEAR'</span>,<span class="st">'CRASH_MONTH'</span>])[<span class="st">'BICYCLE_COUNT'</span>].<span class="bu">sum</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="33">
<pre><code>CRASH_YEAR  CRASH_MONTH
2005        1              13
            2              12
            3              19
            4              63
            5              67
                           ..
2024        8               0
            9               0
            10              0
            11              0
            12              0
Name: BICYCLE_COUNT, Length: 240, dtype: int64</code></pre>
</div>
</div>
<div id="cell-69" class="cell" data-execution_count="34">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>crash_year_month_counts <span class="op">=</span> crash_data.groupby([<span class="st">'CRASH_YEAR'</span>,<span class="st">'CRASH_MONTH'</span>])[<span class="st">'BICYCLE_COUNT'</span>].<span class="bu">sum</span>().unstack()</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>crash_year_month_counts</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="34">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">CRASH_MONTH</th>
<th data-quarto-table-cell-role="th">1</th>
<th data-quarto-table-cell-role="th">2</th>
<th data-quarto-table-cell-role="th">3</th>
<th data-quarto-table-cell-role="th">4</th>
<th data-quarto-table-cell-role="th">5</th>
<th data-quarto-table-cell-role="th">6</th>
<th data-quarto-table-cell-role="th">7</th>
<th data-quarto-table-cell-role="th">8</th>
<th data-quarto-table-cell-role="th">9</th>
<th data-quarto-table-cell-role="th">10</th>
<th data-quarto-table-cell-role="th">11</th>
<th data-quarto-table-cell-role="th">12</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">CRASH_YEAR</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">2005</th>
<td>13</td>
<td>12</td>
<td>19</td>
<td>63</td>
<td>67</td>
<td>86</td>
<td>84</td>
<td>113</td>
<td>104</td>
<td>65</td>
<td>58</td>
<td>14</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2006</th>
<td>19</td>
<td>20</td>
<td>30</td>
<td>53</td>
<td>93</td>
<td>84</td>
<td>101</td>
<td>82</td>
<td>77</td>
<td>76</td>
<td>37</td>
<td>29</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2007</th>
<td>34</td>
<td>9</td>
<td>37</td>
<td>50</td>
<td>104</td>
<td>83</td>
<td>116</td>
<td>95</td>
<td>117</td>
<td>68</td>
<td>37</td>
<td>21</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2008</th>
<td>19</td>
<td>20</td>
<td>40</td>
<td>50</td>
<td>63</td>
<td>106</td>
<td>90</td>
<td>95</td>
<td>87</td>
<td>47</td>
<td>51</td>
<td>38</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2009</th>
<td>17</td>
<td>20</td>
<td>35</td>
<td>63</td>
<td>66</td>
<td>90</td>
<td>108</td>
<td>65</td>
<td>97</td>
<td>64</td>
<td>56</td>
<td>33</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2010</th>
<td>25</td>
<td>10</td>
<td>42</td>
<td>83</td>
<td>89</td>
<td>97</td>
<td>106</td>
<td>101</td>
<td>97</td>
<td>81</td>
<td>46</td>
<td>14</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2011</th>
<td>6</td>
<td>16</td>
<td>29</td>
<td>43</td>
<td>74</td>
<td>123</td>
<td>87</td>
<td>102</td>
<td>74</td>
<td>68</td>
<td>47</td>
<td>34</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2012</th>
<td>19</td>
<td>30</td>
<td>65</td>
<td>63</td>
<td>89</td>
<td>85</td>
<td>94</td>
<td>69</td>
<td>74</td>
<td>61</td>
<td>34</td>
<td>35</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2013</th>
<td>18</td>
<td>12</td>
<td>21</td>
<td>69</td>
<td>90</td>
<td>91</td>
<td>94</td>
<td>109</td>
<td>105</td>
<td>69</td>
<td>42</td>
<td>24</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2014</th>
<td>15</td>
<td>10</td>
<td>19</td>
<td>57</td>
<td>61</td>
<td>106</td>
<td>89</td>
<td>99</td>
<td>99</td>
<td>82</td>
<td>43</td>
<td>42</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2015</th>
<td>8</td>
<td>10</td>
<td>15</td>
<td>56</td>
<td>87</td>
<td>78</td>
<td>93</td>
<td>93</td>
<td>92</td>
<td>70</td>
<td>37</td>
<td>49</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2016</th>
<td>18</td>
<td>33</td>
<td>58</td>
<td>49</td>
<td>70</td>
<td>83</td>
<td>75</td>
<td>85</td>
<td>75</td>
<td>41</td>
<td>66</td>
<td>28</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2017</th>
<td>21</td>
<td>28</td>
<td>32</td>
<td>62</td>
<td>59</td>
<td>66</td>
<td>51</td>
<td>76</td>
<td>76</td>
<td>72</td>
<td>48</td>
<td>27</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2018</th>
<td>18</td>
<td>23</td>
<td>17</td>
<td>29</td>
<td>53</td>
<td>64</td>
<td>59</td>
<td>61</td>
<td>57</td>
<td>58</td>
<td>33</td>
<td>19</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2019</th>
<td>14</td>
<td>7</td>
<td>20</td>
<td>36</td>
<td>45</td>
<td>67</td>
<td>66</td>
<td>75</td>
<td>60</td>
<td>48</td>
<td>29</td>
<td>16</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2020</th>
<td>25</td>
<td>13</td>
<td>29</td>
<td>6</td>
<td>38</td>
<td>53</td>
<td>42</td>
<td>54</td>
<td>47</td>
<td>41</td>
<td>30</td>
<td>10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2021</th>
<td>8</td>
<td>8</td>
<td>22</td>
<td>30</td>
<td>46</td>
<td>63</td>
<td>31</td>
<td>42</td>
<td>43</td>
<td>40</td>
<td>20</td>
<td>15</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2022</th>
<td>8</td>
<td>10</td>
<td>25</td>
<td>16</td>
<td>37</td>
<td>32</td>
<td>31</td>
<td>52</td>
<td>51</td>
<td>33</td>
<td>34</td>
<td>12</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2023</th>
<td>27</td>
<td>20</td>
<td>20</td>
<td>36</td>
<td>56</td>
<td>49</td>
<td>39</td>
<td>59</td>
<td>49</td>
<td>49</td>
<td>29</td>
<td>21</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2024</th>
<td>9</td>
<td>4</td>
<td>5</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-70" class="cell" data-execution_count="35">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>crash_year_month_counts.plot(kind<span class="op">=</span><span class="st">'bar'</span>, figsize<span class="op">=</span>(<span class="dv">20</span>,<span class="dv">4</span>))</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_Exploring_PDOT_Crash_Data_files/figure-html/cell-36-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<section id="key-point-2" class="level4">
<h4 data-anchor-id="key-point-2"><em>Key point</em></h4>
<ul>
<li>Look for patterns in your data!
<ul>
<li>These could be <strong>TRENDS</strong> (an increase or descrease) or <strong>CYCLES</strong> (repeated up and down patterns), etc.</li>
<li>These trends and cycles might be associated with other fields. Here is seems like we observe fewer bikes involved in crashes when the weather is colder.</li>
</ul></li>
<li>What about the time of day?</li>
</ul>
<div id="cell-72" class="cell" data-execution_count="36">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">18</span>,<span class="dv">4</span>))</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>crash_data.groupby([<span class="st">'HOUR_OF_DAY'</span>])[<span class="st">'BICYCLE_COUNT'</span>].<span class="bu">sum</span>().plot.bar()</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_Exploring_PDOT_Crash_Data_files/figure-html/cell-37-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>This plot shows bicycles involved in crashes grouped across all the data by the <code>HOUR_OF_DAY</code></p></li>
<li><p>Definitely seems like a <em>rush hour</em> trend (<code>15-19</code>) that might be worth investigating.</p></li>
<li><p>Notice also the number of <code>99</code> values. These probably indicate that the time of day was not recorded.</p></li>
</ul>
</section>
<section id="well-finish-off-with-a-few-other-grouping-and-aggregating-examples." class="level4">
<h4 data-anchor-id="well-finish-off-with-a-few-other-grouping-and-aggregating-examples.">We’ll finish off with a few other grouping and aggregating examples.</h4>
<ul>
<li>Deaths of cyclists involved in crashes by year and month.</li>
</ul>
<div id="cell-75" class="cell" data-execution_count="37">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> format_xticklabels(plot):</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">'''function to format (year, month) tick labels in a more readable format</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="co">    '''</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>    xticklabels <span class="op">=</span> plot.get_xticklabels()</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>    new_labels <span class="op">=</span> []</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> xtick <span class="kw">in</span> xticklabels:</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>        text <span class="op">=</span> xtick.get_text()</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>        tmatch <span class="op">=</span> re.match(<span class="vs">r'</span><span class="ch">\(</span><span class="kw">(</span><span class="vs">20</span><span class="dv">\d</span><span class="op">{2}</span><span class="kw">)</span><span class="vs">, </span><span class="kw">(</span><span class="dv">\d</span><span class="op">{1,2}</span><span class="kw">)</span><span class="ch">\)</span><span class="vs">'</span>, text)</span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>        mnum <span class="op">=</span> <span class="bu">int</span>(tmatch.group(<span class="dv">2</span>))</span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a>        year <span class="op">=</span> tmatch.group(<span class="dv">1</span>) <span class="cf">if</span> mnum<span class="op">==</span><span class="dv">1</span> <span class="cf">else</span> <span class="st">""</span></span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a>        mabbr <span class="op">=</span> calendar.month_abbr[mnum]</span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a>        xtick.set_text(<span class="ss">f'</span><span class="sc">{</span>year<span class="sc">}</span><span class="ss"> </span><span class="sc">{</span>mabbr<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a>        new_labels.append(xtick)</span>
<span id="cb57-14"><a href="#cb57-14" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb57-15"><a href="#cb57-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> new_labels</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="cell-76" class="cell" data-execution_count="38">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">18</span>,<span class="dv">4</span>))</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>bike_crash <span class="op">=</span> crash_data[crash_data[<span class="st">'BICYCLE_COUNT'</span>]<span class="op">&gt;</span><span class="dv">0</span>]</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>bcrash_plot<span class="op">=</span>bike_crash.groupby([<span class="st">'CRASH_YEAR'</span>,<span class="st">'CRASH_MONTH'</span>])[<span class="st">'FATAL_COUNT'</span>].<span class="bu">sum</span>().plot(kind<span class="op">=</span><span class="st">'bar'</span>, title<span class="op">=</span><span class="st">'Deaths of cyclists involved in crashes by year and month'</span>)</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>bcrash_plot.set_xticklabels(format_xticklabels(bcrash_plot), fontsize<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_Exploring_PDOT_Crash_Data_files/figure-html/cell-39-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>What is the distribution of fatalities across all types of incident?</li>
</ul>
<div id="cell-78" class="cell" data-execution_count="39">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>crash_data[<span class="st">'FATAL_COUNT'</span>].value_counts()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="39">
<pre><code>FATAL_COUNT
0    685996
1      4825
2       207
3        33
4         8
Name: count, dtype: int64</code></pre>
</div>
</div>
<div id="cell-79" class="cell" data-execution_count="40">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>crash_data[<span class="st">'FATAL_COUNT'</span>].hist()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_Exploring_PDOT_Crash_Data_files/figure-html/cell-41-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Which shows where a table can be clearer than a simple plot.</p></li>
<li><p>Subset the data to find incidents where there were exactly 2 fatalities.</p></li>
</ul>
<div id="cell-81" class="cell" data-execution_count="41">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>crash_data[crash_data[<span class="st">'FATAL_COUNT'</span>]<span class="op">==</span><span class="dv">2</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="41">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">CRN</th>
<th data-quarto-table-cell-role="th">ARRIVAL_TM</th>
<th data-quarto-table-cell-role="th">AUTOMOBILE_COUNT</th>
<th data-quarto-table-cell-role="th">BELTED_DEATH_COUNT</th>
<th data-quarto-table-cell-role="th">BELTED_SUSP_SERIOUS_INJ_COUNT</th>
<th data-quarto-table-cell-role="th">BICYCLE_COUNT</th>
<th data-quarto-table-cell-role="th">BICYCLE_DEATH_COUNT</th>
<th data-quarto-table-cell-role="th">BICYCLE_SUSP_SERIOUS_INJ_COUNT</th>
<th data-quarto-table-cell-role="th">BUS_COUNT</th>
<th data-quarto-table-cell-role="th">CHLDPAS_DEATH_COUNT</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">WORK_ZONE_LOC</th>
<th data-quarto-table-cell-role="th">WORK_ZONE_TYPE</th>
<th data-quarto-table-cell-role="th">WZ_CLOSE_DETOUR</th>
<th data-quarto-table-cell-role="th">WZ_FLAGGER</th>
<th data-quarto-table-cell-role="th">WZ_LAW_OFFCR_IND</th>
<th data-quarto-table-cell-role="th">WZ_LN_CLOSURE</th>
<th data-quarto-table-cell-role="th">WZ_MOVING</th>
<th data-quarto-table-cell-role="th">WZ_OTHER</th>
<th data-quarto-table-cell-role="th">WZ_SHLDER_MDN</th>
<th data-quarto-table-cell-role="th">WZ_WORKERS_INJ_KILLED</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">9476</th>
<td>2005138329</td>
<td>NaN</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13966</th>
<td>2005152082</td>
<td>NaN</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14822</th>
<td>2005156668</td>
<td>NaN</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">29642</th>
<td>2005408344</td>
<td>NaN</td>
<td>2</td>
<td>2</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">29732</th>
<td>2005408977</td>
<td>NaN</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">...</th>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">674477</th>
<td>2024054035</td>
<td>1703.0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">675621</th>
<td>2024058423</td>
<td>145.0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">677073</th>
<td>2024064520</td>
<td>336.0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">687365</th>
<td>2024108261</td>
<td>NaN</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">690730</th>
<td>2025007196</td>
<td>1826.0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

<p>207 rows × 99 columns</p>
</div>
</div>
</div>
<ul>
<li><p>So there were 29 crashes where 2 people lost their lives.</p></li>
<li><p>Searching for stories in data will involve exploring the data fulling using these kinds of queries and making observations on the results.</p></li>
</ul>
<p><img src="img/bike_crash.png" class="img-fluid"></p>
<ul>
<li>Here are various summaries of the incidents involving bicycles.</li>
</ul>
<div id="cell-83" class="cell" data-execution_count="42">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># How many bicycle related (cyclists?) deaths were there?</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>crash_data[<span class="st">'BICYCLE_DEATH_COUNT'</span>].value_counts()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="42">
<pre><code>BICYCLE_DEATH_COUNT
0    690948
1       121
Name: count, dtype: int64</code></pre>
</div>
</div>
<div id="cell-84" class="cell" data-execution_count="43">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># How many incidents where there where there was major injury of a cyclist?</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>crash_data[<span class="st">'BICYCLE_SUSP_SERIOUS_INJ_COUNT'</span>].value_counts()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="43">
<pre><code>BICYCLE_SUSP_SERIOUS_INJ_COUNT
0    690507
1       555
2         6
3         1
Name: count, dtype: int64</code></pre>
</div>
</div>
<div id="cell-85" class="cell" data-execution_count="44">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># To give proper context to the bicycle deaths look at the number of incidents</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="co"># where a bicycle was involved</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>crash_data[crash_data[<span class="st">'BICYCLE_COUNT'</span>]<span class="op">&gt;</span><span class="dv">0</span>][<span class="st">'BICYCLE_DEATH_COUNT'</span>].value_counts()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="44">
<pre><code>BICYCLE_DEATH_COUNT
0    11606
1      121
Name: count, dtype: int64</code></pre>
</div>
</div>
<div id="cell-86" class="cell" data-execution_count="45">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The same context for </span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>crash_data[crash_data[<span class="st">'BICYCLE_COUNT'</span>]<span class="op">&gt;</span><span class="dv">0</span>][<span class="st">'BICYCLE_SUSP_SERIOUS_INJ_COUNT'</span>].value_counts()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="45">
<pre><code>BICYCLE_SUSP_SERIOUS_INJ_COUNT
0    11165
1      555
2        6
3        1
Name: count, dtype: int64</code></pre>
</div>
</div>
<div id="cell-87" class="cell" data-execution_count="46">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># filter for biycle death count</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>bicycle_death_filter <span class="op">=</span> crash_data[<span class="st">'BICYCLE_DEATH_COUNT'</span>]<span class="op">&gt;</span><span class="dv">0</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a><span class="co"># filter for serious bike injury</span></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>bicycle_serious_injury_filter <span class="op">=</span> crash_data[<span class="st">'BICYCLE_SUSP_SERIOUS_INJ_COUNT'</span>]<span class="op">&gt;</span><span class="dv">0</span></span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>crash_data[bicycle_death_filter].groupby(<span class="st">'CRASH_YEAR'</span>)[<span class="st">'BICYCLE_DEATH_COUNT'</span>].<span class="bu">sum</span>().plot(kind<span class="op">=</span><span class="st">'bar'</span>)</span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_Exploring_PDOT_Crash_Data_files/figure-html/cell-47-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="cell-88" class="cell" data-execution_count="47">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>bicycle_injuries <span class="op">=</span> crash_data[bicycle_death_filter <span class="op">|</span> bicycle_serious_injury_filter ]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="cell-89" class="cell" data-execution_count="48">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>bike_death_and_injury <span class="op">=</span> bicycle_injuries.groupby(<span class="st">'CRASH_YEAR'</span>)[[<span class="st">'BICYCLE_DEATH_COUNT'</span>, <span class="st">'BICYCLE_SUSP_SERIOUS_INJ_COUNT'</span>]].<span class="bu">sum</span>()</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>bike_death_and_injury</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="48">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">BICYCLE_DEATH_COUNT</th>
<th data-quarto-table-cell-role="th">BICYCLE_SUSP_SERIOUS_INJ_COUNT</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">CRASH_YEAR</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">2005</th>
<td>3</td>
<td>21</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2006</th>
<td>5</td>
<td>30</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2007</th>
<td>8</td>
<td>35</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2008</th>
<td>5</td>
<td>29</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2009</th>
<td>2</td>
<td>32</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2010</th>
<td>8</td>
<td>31</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2011</th>
<td>2</td>
<td>25</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2012</th>
<td>7</td>
<td>20</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2013</th>
<td>2</td>
<td>33</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2014</th>
<td>9</td>
<td>21</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2015</th>
<td>9</td>
<td>26</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2016</th>
<td>3</td>
<td>33</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2017</th>
<td>6</td>
<td>31</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2018</th>
<td>7</td>
<td>26</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2019</th>
<td>5</td>
<td>38</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2020</th>
<td>10</td>
<td>25</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2021</th>
<td>10</td>
<td>35</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2022</th>
<td>4</td>
<td>27</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2023</th>
<td>16</td>
<td>52</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-90" class="cell" data-execution_count="49">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>bike_death_and_injury.plot(stacked<span class="op">=</span><span class="va">True</span>, kind<span class="op">=</span><span class="st">'bar'</span>)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_Exploring_PDOT_Crash_Data_files/figure-html/cell-50-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="cell-91" class="cell" data-execution_count="50">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb75"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># filter for pedestrian accidents</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>ped_involved_filter <span class="op">=</span> crash_data[<span class="st">'PED_COUNT'</span>]<span class="op">&gt;</span><span class="dv">0</span></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>ped_accidents <span class="op">=</span> crash_data[ped_involved_filter]</span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>ped_accident_count <span class="op">=</span> ped_accidents.groupby(<span class="st">'CRASH_YEAR'</span>)[[<span class="st">'PED_DEATH_COUNT'</span>, <span class="st">'PED_SUSP_SERIOUS_INJ_COUNT'</span>]].<span class="bu">sum</span>()</span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a>ped_accident_count</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="50">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">PED_DEATH_COUNT</th>
<th data-quarto-table-cell-role="th">PED_SUSP_SERIOUS_INJ_COUNT</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">CRASH_YEAR</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">2005</th>
<td>53</td>
<td>135</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2006</th>
<td>66</td>
<td>141</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2007</th>
<td>62</td>
<td>138</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2008</th>
<td>51</td>
<td>126</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2009</th>
<td>63</td>
<td>132</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2010</th>
<td>46</td>
<td>149</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2011</th>
<td>63</td>
<td>141</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2012</th>
<td>66</td>
<td>137</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2013</th>
<td>60</td>
<td>130</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2014</th>
<td>63</td>
<td>111</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2015</th>
<td>48</td>
<td>138</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2016</th>
<td>68</td>
<td>151</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2017</th>
<td>63</td>
<td>171</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2018</th>
<td>83</td>
<td>173</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2019</th>
<td>63</td>
<td>229</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2020</th>
<td>69</td>
<td>165</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2021</th>
<td>77</td>
<td>219</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2022</th>
<td>93</td>
<td>240</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2023</th>
<td>89</td>
<td>244</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2024</th>
<td>7</td>
<td>26</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-92" class="cell" data-execution_count="51">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>ped_accident_count.plot(stacked<span class="op">=</span><span class="va">True</span>, kind<span class="op">=</span><span class="st">'bar'</span>)</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_Exploring_PDOT_Crash_Data_files/figure-html/cell-52-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="cell-93" class="cell" data-execution_count="52">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>data_dictionary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="52">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Column_Name</th>
<th data-quarto-table-cell-role="th">Description</th>
<th data-quarto-table-cell-role="th">Type</th>
<th data-quarto-table-cell-role="th">Length</th>
<th data-quarto-table-cell-role="th">Constraints</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>ARRIVAL_TM</td>
<td>Time police arrived at the scene</td>
<td>TEXT</td>
<td>4.0</td>
<td>HHMM</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>AUTOMOBILE_COUNT</td>
<td>Total amount of Automobiles Involved</td>
<td>NUMBER</td>
<td>2.0</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>BELTED_DEATH_COUNT</td>
<td>Total Deaths of belted occupants</td>
<td>NUMBER</td>
<td>2.0</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>BELTED_SUSP_SERIOUS_INJ_COUNT</td>
<td>Total Suspected Serious Injuries of belted occ...</td>
<td>NUMBER</td>
<td>2.0</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>BICYCLE_COUNT</td>
<td>Total amount of Bicycles involved</td>
<td>NUMBER</td>
<td>2.0</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">...</th>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">94</th>
<td>WZ_LN_CLOSURE</td>
<td>Did Work zone have a lane closure?</td>
<td>TEXT</td>
<td>1.0</td>
<td>1=Y, 0 = N</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">95</th>
<td>WZ_MOVING</td>
<td>Was there moving work in the zone?</td>
<td>TEXT</td>
<td>1.0</td>
<td>1=Y, 0 = N</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">96</th>
<td>WZ_OTHER</td>
<td>Was this a special type of work zone?</td>
<td>TEXT</td>
<td>1.0</td>
<td>1=Y, 0 = N</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">97</th>
<td>WZ_SHLDER_MDN</td>
<td>Was a median/shoulder in the zone?</td>
<td>TEXT</td>
<td>1.0</td>
<td>1=Y, 0 = N</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">98</th>
<td>WZ_WORKERS_INJ_KILLED</td>
<td>Were any Work Zone workers injured or\rkilled ...</td>
<td>TEXT</td>
<td>1.0</td>
<td>1=Y, 0 = N</td>
</tr>
</tbody>
</table>

<p>99 rows × 5 columns</p>
</div>
</div>
</div>
</section>
</section>
<section id="geolocation" class="level3">
<h3 data-anchor-id="geolocation">Geolocation</h3>
<ul>
<li>There are two variables in the data set that recorded the geospatial position of the recorded crash incident:
<ul>
<li><code>DEC_LATITUDE</code></li>
<li><code>DEC_LONGITUDE</code></li>
</ul></li>
</ul>
<div id="cell-95" class="cell" data-execution_count="53">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>data_dictionary.set_index(<span class="st">'Column_Name'</span>).loc[[<span class="st">'DEC_LATITUDE'</span>, <span class="st">'DEC_LONGITUDE'</span>]]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="53">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Description</th>
<th data-quarto-table-cell-role="th">Type</th>
<th data-quarto-table-cell-role="th">Length</th>
<th data-quarto-table-cell-role="th">Constraints</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Column_Name</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">DEC_LATITUDE</th>
<td>Decimal format of the Latitude</td>
<td>NUMBER</td>
<td>2.4</td>
<td>Latitude expressed in decimal degrees 99.9999</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">DEC_LONGITUDE</th>
<td>Decimal format of the Longitude</td>
<td>NUMBER</td>
<td>2.4</td>
<td>Longitude expressed in decimal degrees 99.9999</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-96" class="cell" data-execution_count="54">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>bicycle_injuries[[<span class="st">'DEC_LATITUDE'</span>, <span class="st">'DEC_LONGITUDE'</span>]]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="54">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">DEC_LATITUDE</th>
<th data-quarto-table-cell-role="th">DEC_LONGITUDE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">1056</th>
<td>39.964656</td>
<td>-75.236198</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5222</th>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">7065</th>
<td>39.867225</td>
<td>-75.377383</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9223</th>
<td>39.923399</td>
<td>-75.299797</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10257</th>
<td>40.196944</td>
<td>-75.115000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">...</th>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">659242</th>
<td>39.981154</td>
<td>-75.831219</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">659576</th>
<td>40.149948</td>
<td>-75.230230</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">660165</th>
<td>39.981650</td>
<td>-75.283684</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">660582</th>
<td>39.829778</td>
<td>-75.393865</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">660779</th>
<td>40.039469</td>
<td>-75.057075</td>
</tr>
</tbody>
</table>

<p>683 rows × 2 columns</p>
</div>
</div>
</div>
<ul>
<li>If we plot these as a scatter plot you get an idea of how the data might be used to look for geospatial patterns</li>
</ul>
<div id="cell-98" class="cell" data-execution_count="55">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>bicycle_injuries.plot(x<span class="op">=</span><span class="st">'DEC_LATITUDE'</span>, y<span class="op">=</span><span class="st">'DEC_LONGITUDE'</span>, kind<span class="op">=</span><span class="st">'scatter'</span>)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_Exploring_PDOT_Crash_Data_files/figure-html/cell-56-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<section id="using-a-base-layer" class="level4">
<h4 data-anchor-id="using-a-base-layer">Using a base layer</h4>
<ul>
<li>Various <code>geojson</code> files are available that define shapes for regions like <em>states</em>, <em>counties</em>, <em>zip codes</em>, <em>census tracts</em>, etc.</li>
</ul>
<div id="cell-100" class="cell" data-execution_count="56">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb81"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>philly_gdf <span class="op">=</span> gpd.read_file(<span class="st">'data/philadelphia_zip_boundaries.geojson'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="cell-101" class="cell" data-execution_count="57">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>philly_gdf.plot(color<span class="op">=</span><span class="st">'#F0F0F0'</span>, edgecolor<span class="op">=</span><span class="st">'#202020'</span>)</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="co">#plt.show()</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_Exploring_PDOT_Crash_Data_files/figure-html/cell-58-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="converting-a-pandas-data-frame-to-a-geopandas-data-frame" class="level4">
<h4 data-anchor-id="converting-a-pandas-data-frame-to-a-geopandas-data-frame">Converting a <code>pandas</code> data frame to a <code>geopandas</code> data frame</h4>
<ul>
<li>But to make the best use of geolocation variables like <code>DEC_LATITUDE</code> and <code>DEC_LONGITUDE</code>, we need to translate them into a <code>geometry</code> data type.</li>
</ul>
<div id="cell-103" class="cell" data-execution_count="58">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb83"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>geom<span class="op">=</span>gpd.points_from_xy(bicycle_injuries[<span class="st">'DEC_LONGITUDE'</span>],</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>                  bicycle_injuries[<span class="st">'DEC_LATITUDE'</span>]</span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>                  )</span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>bicycle_injuries_gdf<span class="op">=</span>gpd.GeoDataFrame(bicycle_injuries, geometry<span class="op">=</span>geom)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Then we can combine both the base layer map and the points</li>
</ul>
<div id="cell-105" class="cell" data-execution_count="59">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>base<span class="op">=</span>philly_gdf.plot(color<span class="op">=</span><span class="st">'white'</span>, </span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>                     edgecolor<span class="op">=</span><span class="st">'gray'</span>, figsize<span class="op">=</span>(<span class="dv">8</span>,<span class="dv">8</span>))</span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>bicycle_injuries_gdf.plot(ax<span class="op">=</span>base, </span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>                          markersize<span class="op">=</span><span class="dv">8</span>, </span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a>                          column<span class="op">=</span><span class="st">'CRASH_YEAR'</span>, </span>
<span id="cb84-7"><a href="#cb84-7" aria-hidden="true" tabindex="-1"></a>                          categorical<span class="op">=</span><span class="va">True</span>, </span>
<span id="cb84-8"><a href="#cb84-8" aria-hidden="true" tabindex="-1"></a>                          legend<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb84-9"><a href="#cb84-9" aria-hidden="true" tabindex="-1"></a>                          legend_kwds<span class="op">=</span>{<span class="st">'bbox_to_anchor'</span>: (<span class="fl">1.05</span>, <span class="dv">1</span>), <span class="st">'loc'</span>: <span class="st">'upper left'</span>}</span>
<span id="cb84-10"><a href="#cb84-10" aria-hidden="true" tabindex="-1"></a>                         )</span>
<span id="cb84-11"><a href="#cb84-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-12"><a href="#cb84-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_Exploring_PDOT_Crash_Data_files/figure-html/cell-60-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Here we notice that we have a Philadelphia city map but data from DISTRICT 6 for the crash data.</li>
<li>So we want to filter using <code>COUNTY</code> and value 67</li>
</ul>
<div id="cell-107" class="cell" data-execution_count="60">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb85"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>phil_city_filter <span class="op">=</span> bicycle_injuries_gdf[<span class="st">'COUNTY'</span>]<span class="op">==</span><span class="dv">67</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="cell-108" class="cell" data-execution_count="61">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>base<span class="op">=</span>philly_gdf.plot(color<span class="op">=</span><span class="st">'white'</span>, </span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>                     edgecolor<span class="op">=</span><span class="st">'gray'</span>, figsize<span class="op">=</span>(<span class="dv">8</span>,<span class="dv">8</span>))</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>bicycle_injuries_gdf[phil_city_filter].plot(ax<span class="op">=</span>base, </span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>                          markersize<span class="op">=</span><span class="dv">8</span>, </span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a>                          column<span class="op">=</span><span class="st">'CRASH_YEAR'</span>, </span>
<span id="cb86-7"><a href="#cb86-7" aria-hidden="true" tabindex="-1"></a>                          categorical<span class="op">=</span><span class="va">True</span>, </span>
<span id="cb86-8"><a href="#cb86-8" aria-hidden="true" tabindex="-1"></a>                          legend<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb86-9"><a href="#cb86-9" aria-hidden="true" tabindex="-1"></a>                          legend_kwds<span class="op">=</span>{<span class="st">'bbox_to_anchor'</span>: (<span class="fl">1.05</span>, <span class="dv">1</span>), <span class="st">'loc'</span>: <span class="st">'upper left'</span>}</span>
<span id="cb86-10"><a href="#cb86-10" aria-hidden="true" tabindex="-1"></a>                         )</span>
<span id="cb86-11"><a href="#cb86-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-12"><a href="#cb86-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_Exploring_PDOT_Crash_Data_files/figure-html/cell-62-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="aggregating-crash-incidents-by-geospatial-regions" class="level3">
<h3 data-anchor-id="aggregating-crash-incidents-by-geospatial-regions">Aggregating crash incidents by geospatial regions</h3>
<ul>
<li>The point data shown above (and the categorical labels by color) are difficult make much sense of</li>
<li>One of the powerful things you can do with <code>geopandas</code> is to aggregate data using the available geometry.</li>
<li>This means you can do the equivalent of a <strong>GROUP BY</strong> operation using geolocation, e.g.
<ul>
<li>count the number of bicycle crash incidents by the zip code they occurred in</li>
</ul></li>
</ul>
<div id="cell-110" class="cell" data-execution_count="62">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb87"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># filter bike injuries for just city and set CRS for geometry</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>phil_bicycle_injuries_gdf<span class="op">=</span>bicycle_injuries_gdf[phil_city_filter].set_crs(<span class="st">'EPSG:4326'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="spatial-joins" class="level4">
<h4 data-anchor-id="spatial-joins">Spatial Joins</h4>
<ul>
<li>A <strong>SPATIAL JOIN</strong> (<code>.sjoin</code>) allows you merge two geodataframes using a common spatial shape.</li>
<li>Here we want to use the boundaries of zip codes to group together the latitude and longitude points for the crash incidents.</li>
</ul>
<div id="cell-112" class="cell" data-execution_count="63">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>bgdf<span class="op">=</span>gpd.sjoin(philly_gdf, phil_bicycle_injuries_gdf)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>This will give us a ZIP CODE reference for each incident</li>
<li>But we actually want to count up the number of incidents per area</li>
<li>To do this we use <code>.dissolve</code> function</li>
</ul>
<div id="cell-114" class="cell" data-execution_count="64">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb89"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>bgdf2<span class="op">=</span>bgdf.dissolve(by<span class="op">=</span><span class="st">'listname'</span>, aggfunc<span class="op">=</span><span class="st">'count'</span>)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>bgdf2.sort_values(<span class="st">'DISTRICT'</span>, ascending<span class="op">=</span><span class="va">False</span>)[[<span class="st">'geometry'</span>,<span class="st">'name'</span>]].head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="64">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">geometry</th>
<th data-quarto-table-cell-role="th">name</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">listname</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">University City</th>
<td>POLYGON ((-75.17935 39.95822, -75.17935 39.957...</td>
<td>18</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Logan Square</th>
<td>POLYGON ((-75.1759 39.96418, -75.17444 39.9640...</td>
<td>12</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Rittenhouse</th>
<td>POLYGON ((-75.16876 39.94404, -75.17033 39.944...</td>
<td>11</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Hunting Park</th>
<td>POLYGON ((-75.12598 40.01386, -75.12234 40.013...</td>
<td>9</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Haddington</th>
<td>POLYGON ((-75.22457 39.96492, -75.22421 39.963...</td>
<td>9</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-115" class="cell" data-execution_count="65">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>fig<span class="op">=</span>philly_gdf.plot(color<span class="op">=</span><span class="st">'white'</span>, </span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>                     edgecolor<span class="op">=</span><span class="st">'lightgray'</span>, figsize<span class="op">=</span>(<span class="dv">6</span>,<span class="dv">6</span>))</span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a>bgdf2.plot(ax<span class="op">=</span>fig,column<span class="op">=</span><span class="st">'name'</span>, cmap<span class="op">=</span><span class="st">'Reds'</span>, </span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a>           legend<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb90-6"><a href="#cb90-6" aria-hidden="true" tabindex="-1"></a>           legend_kwds<span class="op">=</span>{<span class="st">'shrink'</span>: <span class="fl">0.5</span>, </span>
<span id="cb90-7"><a href="#cb90-7" aria-hidden="true" tabindex="-1"></a>                        <span class="st">'label'</span>: <span class="st">'Number of injuries'</span>}     </span>
<span id="cb90-8"><a href="#cb90-8" aria-hidden="true" tabindex="-1"></a>          )</span>
<span id="cb90-9"><a href="#cb90-9" aria-hidden="true" tabindex="-1"></a>fig.axis(<span class="st">'off'</span>)</span>
<span id="cb90-10"><a href="#cb90-10" aria-hidden="true" tabindex="-1"></a>fig.set_title(<span class="st">'Where did incidents resulting in bicycle injuries </span><span class="ch">\n</span><span class="st">occur in Philadelphia during 2005-2024?'</span>)</span>
<span id="cb90-11"><a href="#cb90-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-12"><a href="#cb90-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_Exploring_PDOT_Crash_Data_files/figure-html/cell-66-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="some-old-resources-for-use-in-looking-for-stories-in-these-data" class="level2">
<h2 data-anchor-id="some-old-resources-for-use-in-looking-for-stories-in-these-data">Some (old) resources for use in looking for stories in these data</h2>
<section id="news-and-other-sites" class="level3">
<h3 data-anchor-id="news-and-other-sites">News and other sites</h3>
<ul>
<li><p>https://www.phillytrib.com/news/local_news/philly-s-riskiest-deadliest-roads-in-black-and-brown-neighborhoods/article_1d03b88e-2edf-5cbd-9f42-dd5eddf8fedf.html</p></li>
<li><p>https://usa.streetsblog.org/2018/02/12/philadelphias-boulevard-of-death/</p></li>
<li><p>https://billypenn.com/2017/02/06/how-roosevelt-boulevard-became-the-most-dangerous-road-in-philadelphia/</p></li>
<li><p>KnowPA - infoviz example dashboards - http://www.knowpa.com/</p></li>
</ul>
</section>
<section id="legal-firms-citing-crash-data" class="level3">
<h3 data-anchor-id="legal-firms-citing-crash-data">Legal firms citing crash data</h3>
<blockquote class="blockquote">
<p>Roosevelt Boulevard, Philadelphia, Pennsylvania</p>
<p>While the other roads mentioned on this list are highways, Roosevelt Boulevard in Philadelphia is included because of its notoriety as one of the most dangerous thoroughfares in America. The boulevard consists of six 12-foot wide lanes in each direction, and drivers regularly exceed the posted 45 miles per hour and take the road’s dangerous curves far too fast. The boulevard also has two of the nation’s most dangerous intersections, where confused drivers frequently turn into the wrong three-lane stretch of traffic.</p>
</blockquote>
<p>https://www.hg.org/legal-articles/5-of-the-most-dangerous-roads-in-the-u-s–32057</p>
<blockquote class="blockquote">
<p>Pennsylvania roads are dangerous, and with its large concentration of population, Philadelphia has the greatest number of crash-related deaths. In fact, according to PennDOT data on fatal car accidents, Philadelphia had more than a quarter of the road segments that were among the state’s most deadly from 2015-2017. During this period, Philly had 24 road segments with 155 total fatal collisions, leading to 167 deaths. This amounted to about a third of the segments with at least four deaths in the entire state.</p>
</blockquote>
<p>https://www.wnwlaw.com/philly-four-pennsylvanias-ten-deadliest-roads/</p>
<ul>
<li>Study by law firm</li>
</ul>
<p>https://www.dallashartman.com/blog/2019/01/deadly-roads-pa/</p>


</section>
</section>


 <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/dpark2380\.github\.io\/comm3180_S26_Blog\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
 <!-- /content -->




</body></html>