<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Daniel Park">
<meta name="dcterms.date" content="2026-02-25">
<meta name="description" content="placeholder">

<title>Blog 04: Analysis of Pennsylvania Crash Data – Daniel’s Data Stories</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-fadc7197feb5b0cc1514f5252acd9486.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Daniel’s Data Stories</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/dpark2380/comm3180_S26_Blog"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Blog 04: Analysis of Pennsylvania Crash Data</h1>
                  <div>
        <div class="description">
          placeholder
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">car crashes</div>
                <div class="quarto-category">data stories</div>
                <div class="quarto-category">data visualization</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Daniel Park </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">February 25, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p>Road crashes are a major public safety issue in large cities, where dense traffic, complex road networks, and pedestrian activity interact in unpredictable ways. Philadelphia has long struggled with dangerous road corridors, particularly wide arterial roads where high vehicle speeds mix with local traffic and pedestrian activity.</p>
<p>Some roads in the city have developed a particularly strong reputation for danger. Roosevelt Boulevard, for example, is frequently cited as one of the most dangerous roads in Philadelphia. According to an article by the Philadelphia Tribune, “between 2011 and 2015, about 13 percent of the city’s traffic fatalities occurred on the 16-mile stretch of Roosevelt Boulevard running from Hunting Park to just beyond the city line in Bensalem. During that period the corridor saw more than 60 deaths and roughly 4,700 injuries, with pedestrians accounting for about one-third of those killed on the 12-lane road.” Other analyses of PennDOT crash data have also noted that Philadelphia contains a disproportionate share of Pennsylvania’s deadliest road segments. Additionally, according to WarperNewman, sections of Broad Street frequently appear among the most dangerous in the state.</p>
<p>In this post, I analyze nearly two decades of Pennsylvania Department of Transportation (PennDOT) crash records to better understand patterns in Philadelphia traffic collisions. Using geospatial analysis, I first examine how crashes are distributed across the city and how crash severity changes over time and by time of day. I will then take a closer look at several major corridors, including Roosevelt Boulevard, Broad Street, to investigate whether the patterns in the data support their reputation as some of the most dangerous roads in the region.</p>
<p>In response to persistent fatalities on Roosevelt Boulevard, the city has introduced automated speed enforcement cameras along sections of the corridor in an effort to reduce speeding and improve safety. Early reports suggest that these cameras have significantly reduced fatal crashes, raising an important question: how much can targeted policy interventions influence road safety outcomes?</p>
<p>Sources:</p>
<p><a href="https://www.phillytrib.com/news/local_news/philly-s-riskiest-deadliest-roads-in-black-and-brown-neighborhoods/article_1d03b88e-2edf-5cbd-9f42-dd5eddf8fedf.html">Philly’s riskiest and deadliest roads are concentrated in Black and Brown neighborhoods</a></p>
<p><a href="https://www.hg.org/legal-articles/5-of-the-most-dangerous-roads-in-the-u-s--32057">5 of the Most Dangerous Roads in the U.S.</a></p>
<div id="cell-2" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> geopandas <span class="im">as</span> gpd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> camelot</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> calendar</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> re</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> shapely.geometry <span class="im">import</span> Point</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="cell-3" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>crash_data <span class="op">=</span> pd.read_csv(<span class="st">"data/PDOT_crash_data_2005_2024.csv"</span>, low_memory<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>philly_zip <span class="op">=</span> gpd.read_file(<span class="st">"data/philadelphia_zip_boundaries.geojson"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>data_dictionary <span class="op">=</span> pd.read_csv(<span class="st">'data/data_dictionary.csv'</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>div_gdf <span class="op">=</span> gpd.read_file(<span class="st">"data/Political_Divisions.geojson"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>streets <span class="op">=</span> gpd.read_file(<span class="st">"data/Street_Centerline.geojson"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="spatial-distribution-of-crashes-across-philadelphia" class="level2">
<h2 class="anchored" data-anchor-id="spatial-distribution-of-crashes-across-philadelphia">Spatial distribution of crashes across Philadelphia</h2>
<div id="cell-5" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>phil_filter <span class="op">=</span> crash_data[<span class="st">'COUNTY'</span>] <span class="op">==</span> <span class="dv">67</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>phil_crashes <span class="op">=</span> crash_data[phil_filter].copy()</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># remove rows without decimal coordinates</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>phil_crashes <span class="op">=</span> phil_crashes.dropna(subset<span class="op">=</span>[<span class="st">'DEC_LATITUDE'</span>,<span class="st">'DEC_LONGITUDE'</span>])</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>phil_crashes.shape</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>geom <span class="op">=</span> gpd.points_from_xy(phil_crashes[<span class="st">'DEC_LONGITUDE'</span>], phil_crashes[<span class="st">'DEC_LATITUDE'</span>])</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>phil_crashes_gdf <span class="op">=</span> gpd.GeoDataFrame(phil_crashes, geometry<span class="op">=</span>geom).set_crs(<span class="st">'EPSG:4326'</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>philly_zip <span class="op">=</span> gpd.read_file(<span class="st">"data/philadelphia_zip_boundaries.geojson"</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>base <span class="op">=</span> philly_zip.plot(color<span class="op">=</span><span class="st">'white'</span>, edgecolor<span class="op">=</span><span class="st">'lightgray'</span>, figsize<span class="op">=</span>(<span class="dv">7</span>,<span class="dv">7</span>))</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>phil_crashes_gdf.sample(<span class="dv">8000</span>).plot(ax<span class="op">=</span>base, markersize<span class="op">=</span><span class="dv">1</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>base.axis(<span class="st">'off'</span>)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Sample of 8,000 crash locations in Philadelphia, 2005–2024"</span>)</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="DOW4_crash-Copy1_files/figure-html/cell-4-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>From the above spatial distribution of 8,000 sampled crashes across Philadelphia, we can see several clear patterns. Collisions are not evenly distributed across the city; instead, they cluster heavily along major transportation corridors and in the dense street grid of Center City and North Philadelphia. These areas contain high traffic volumes, frequent intersections, and significant pedestrian activity, all of which increase the likelihood of conflict between road users.</p>
<p>Several prominent linear patterns are also visible in the map, where crashes align along major arterial roads that cut across the city. We can see that the Schuylkill Expressway running along the river has a constant band of incidents, and we can see a strong band along Vine St Expressway which connects the I-76 to the Delaware Expressway, I-95.</p>
<p>Passing straight through north from the middle of Center City, we can observe the band of incidents along Broad Street, then moving north east, we see Roosevelt Boulevard, which was one the most dangerous roads from 2011-2015, with a strong band of incidents heading north.</p>
<p>These patterns highlight an important feature of urban road safety: risk is often concentrated along specific corridors rather than evenly spread across the network, as outlined in the articles. In the next section, we examine several of these corridors in more detail, beginning with Roosevelt Boulevard, which has long been regarded as one of the most dangerous roads in Philadelphia.</p>
<div id="cell-7" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># spatial join: crashes -&gt; zip polygons</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>zjoin <span class="op">=</span> gpd.sjoin(philly_zip, phil_crashes_gdf, how<span class="op">=</span><span class="st">'left'</span>, predicate<span class="op">=</span><span class="st">'contains'</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># dissolve by zip and count CRN values</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>zip_counts <span class="op">=</span> zjoin.dissolve(by<span class="op">=</span><span class="st">'listname'</span>, aggfunc<span class="op">=</span>{<span class="st">'CRN'</span>: <span class="st">'count'</span>})</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>zip_counts <span class="op">=</span> zip_counts.rename(columns<span class="op">=</span>{<span class="st">'CRN'</span>: <span class="st">'crash_count'</span>})</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>,<span class="dv">8</span>))</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>philly_zip.plot(ax<span class="op">=</span>ax, color<span class="op">=</span><span class="st">'white'</span>, edgecolor<span class="op">=</span><span class="st">'lightgray'</span>)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>zip_counts.plot(</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    ax<span class="op">=</span>ax,</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    column<span class="op">=</span><span class="st">'crash_count'</span>,</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>    cmap<span class="op">=</span><span class="st">'coolwarm'</span>,   <span class="co"># blue low -&gt; red high</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>    legend<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>    legend_kwds<span class="op">=</span>{<span class="st">'shrink'</span>: <span class="fl">0.6</span>, <span class="st">'label'</span>: <span class="st">'Crash count'</span>, <span class="st">'pad'</span>: <span class="fl">0.02</span>}</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Where are crashes concentrated?</span><span class="ch">\n</span><span class="st">(Philadelphia ZIP areas, 2005–2024)"</span>, pad<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>ax.axis(<span class="st">'off'</span>)</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="DOW4_crash-Copy1_files/figure-html/cell-5-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>While the previous map shows the precise locations of individual crashes, it can be difficult to identify broader geographic patterns when thousands of points overlap across the city. Aggregating crashes by ZIP code helps reveal where incidents are most concentrated across Philadelphia.</p>
<p>Several ZIP codes in and around Center City record the highest total number of crashes. This is true because dense, urban neighbourhoods contain a tightly packed street grid, heavy traffic volumes, and many intersections where vehicles, cyclists, and pedestrians interact frequently. These conditions increase the number of potential conflict points, leading to more incidents overall.</p>
<p>However, a higher number of crashes does not necessarily imply more severe outcomes. In dense areas, traffic tends to move more slowly due to congestion, traffic lights, and frequent intersections. While minor collisions may occur more often in these environments, lower speeds typically reduce the likelihood of fatal outcomes.</p>
<p>In contrast, many of the most severe crashes occur on large arterial roads where vehicles travel at higher speeds and traffic flows more continuously. These wide corridors carry large volumes of vehicles and often combine fast-moving traffic with turning movements and pedestrian crossings. As a result, while dense neighbourhoods may experience more incidents overall, the most dangerous crashes frequently occur on major roadways such as Roosevelt Boulevard and other high-speed corridors across the city.</p>
</section>
<section id="how-are-crashes-and-fatalities-distributed-over-time-in-philadelphia" class="level2">
<h2 class="anchored" data-anchor-id="how-are-crashes-and-fatalities-distributed-over-time-in-philadelphia">How are crashes and fatalities distributed over time in Philadelphia?</h2>
<p>We have observed where crashes are most likely to occur, and now we will aim to look at how the number of crashes changes over the period of the whole day, and see if they are correlated in any way to the distribution of fatalities.</p>
<div id="cell-10" class="cell" data-execution_count="31">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">9</span>,<span class="dv">4</span>))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>plt.plot(hour.index, hour[<span class="st">'crashes'</span>], marker<span class="op">=</span><span class="st">'o'</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Number of crashes by hour (Philadelphia, 2005–2024)"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Hour of day"</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Crashes"</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>plt.xticks(<span class="bu">range</span>(<span class="dv">0</span>,<span class="dv">24</span>))</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="DOW4_crash-Copy1_files/figure-html/cell-6-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The hourly patterns reveal an important distinction between the frequency of crashes and their severity. The total number of crashes rises sharply during the daytime and peaks in the late afternoon, around the evening commuting period between roughly 3 PM and 6 PM. These hours correspond to the highest traffic volumes as people travel to and from work, increasing the number of potential interactions between vehicles.</p>
<p>However, we can see that during the night and early morning, the number of crashes per hour is relatively stable, mostly ranging from 200-300 over the whole 20 year period, with very little crashes having happened around 4 to 5 am in the morning. This reflects the much lower traffic volumes during these hours, when far fewer vehicles are on the road compared with the daytime commuting periods, even though the crashes that do occur may be more severe, which we will observe now.</p>
<div id="cell-12" class="cell" data-execution_count="32">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fatalities by hour</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">9</span>,<span class="dv">4</span>))</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>plt.plot(hour.index, hour[<span class="st">'fatalities'</span>], marker<span class="op">=</span><span class="st">'o'</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Number of fatalities by hour (Philadelphia, 2005–2024)"</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Hour of day"</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Fatalities"</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>plt.xticks(<span class="bu">range</span>(<span class="dv">0</span>,<span class="dv">24</span>))</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="DOW4_crash-Copy1_files/figure-html/cell-7-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>When first observing the graph of fatalities by hour, we can see that it follows a very different pattern from the earlier crash distribution, appearing almost like a mirrored version of the original graph.</p>
<p>Fatalities are most concentrated during late-night and evening hours. The highest counts occur around 1 AM and 10 PM, with several other elevated values between 7 PM and midnight. These hours correspond to periods when traffic volumes are lower, but factors such as reduced visibility, driver fatigue, and impaired driving may contribute to the higher severity of crashes during these times.</p>
<p>In contrast, the middle of the day shows relatively few fatalities, particularly between 9 AM and noon, where the counts remain close to one fatality per hour across the entire dataset. This suggests that although crashes are more common during daytime traffic periods, they are less likely to result in fatal outcomes. Congestion, traffic lights, and lower average speeds likely reduce the severity of collisions during these hours.</p>
<p>Combining the insights from the two graphs, a clear pattern emerges: while most crashes occur during the daytime when traffic volumes are highest, fatal crashes are more concentrated during nighttime hours, when vehicles are able to travel at higher speeds and risky driving conditions are more likely.</p>
</section>
<section id="roosevelt-boulevard-philadelphias-most-dangerous-road" class="level2">
<h2 class="anchored" data-anchor-id="roosevelt-boulevard-philadelphias-most-dangerous-road">Roosevelt Boulevard: Philadelphia’s most dangerous road</h2>
<p>Now we will take a deeper dive into what was considered Philadelphia’s most dangerous road, testing the claims made by The Philadelphia Tribune which stated that “between 2011 and 2015, 13 percent of the city’s traffic fatalities” have happened on the boulevard, with “pedestrians ma(king) up one-third of those killed on the 12-lane road.”</p>
<div id="cell-15" class="cell" data-execution_count="33">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>BUFFER_FT <span class="op">=</span> <span class="dv">100</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>CRS_FEET <span class="op">=</span> <span class="dv">2272</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 1) Find Roosevelt BLVD segments + Roosevelt ramps</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>rb_main <span class="op">=</span> streets[</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    (streets[<span class="st">"st_name"</span>].fillna(<span class="st">""</span>).<span class="bu">str</span>.upper().<span class="bu">str</span>.strip() <span class="op">==</span> <span class="st">"ROOSEVELT"</span>) <span class="op">&amp;</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    (streets[<span class="st">"st_type"</span>].fillna(<span class="st">""</span>).<span class="bu">str</span>.upper().<span class="bu">str</span>.strip() <span class="op">==</span> <span class="st">"BLVD"</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>].copy()</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>rb_ramps <span class="op">=</span> streets[</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    (streets[<span class="st">"st_name"</span>].fillna(<span class="st">""</span>).<span class="bu">str</span>.upper().<span class="bu">str</span>.contains(<span class="st">"ROOSEVELT"</span>, na<span class="op">=</span><span class="va">False</span>)) <span class="op">&amp;</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    (streets[<span class="st">"st_type"</span>].fillna(<span class="st">""</span>).<span class="bu">str</span>.upper().<span class="bu">str</span>.strip() <span class="op">==</span> <span class="st">"RAMP"</span>)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>].copy()</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>rb <span class="op">=</span> pd.concat([rb_main, rb_ramps], ignore_index<span class="op">=</span><span class="va">True</span>).to_crs(epsg<span class="op">=</span>CRS_FEET)</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a><span class="co"># 2) Buffer into a corridor polygon</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>rb_buf <span class="op">=</span> gpd.GeoDataFrame(geometry<span class="op">=</span>rb.<span class="bu">buffer</span>(BUFFER_FT), crs<span class="op">=</span>rb.crs)</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a><span class="co"># 3) Crashes (2011–2015) projected to feet CRS</span></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>city_11_15 <span class="op">=</span> phil_crashes_gdf.query(<span class="st">"2011 &lt;= CRASH_YEAR &lt;= 2015"</span>).to_crs(epsg<span class="op">=</span>CRS_FEET)</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>city_fatalities <span class="op">=</span> city_11_15[<span class="st">"FATAL_COUNT"</span>].<span class="bu">sum</span>()</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a><span class="co"># 4) Join crashes within corridor + dedupe</span></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>rb_joined_11_15 <span class="op">=</span> gpd.sjoin(city_11_15, rb_buf, predicate<span class="op">=</span><span class="st">"within"</span>).drop_duplicates(<span class="st">"CRN"</span>)</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a><span class="co"># 5) Stats</span></span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>rb_fatalities_11_15 <span class="op">=</span> rb_joined_11_15[<span class="st">"FATAL_COUNT"</span>].<span class="bu">sum</span>()</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>rb_share_11_15 <span class="op">=</span> rb_fatalities_11_15 <span class="op">/</span> city_fatalities</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>rb_injuries_11_15 <span class="op">=</span> rb_joined_11_15[<span class="st">"TOT_INJ_COUNT"</span>].<span class="bu">sum</span>()</span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>rb_ped_deaths_11_15 <span class="op">=</span> rb_joined_11_15[<span class="st">"PED_DEATH_COUNT"</span>].<span class="bu">sum</span>()</span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>rb_ped_share_11_15 <span class="op">=</span> rb_ped_deaths_11_15 <span class="op">/</span> rb_fatalities_11_15</span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a>rb_summary <span class="op">=</span> pd.DataFrame({</span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Metric"</span>: [</span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Total Number of Crashes"</span>, <span class="st">"Fatalities"</span>, <span class="st">"Share of city fatalities"</span>, <span class="st">"Injuries"</span>, <span class="st">"Pedestrian deaths"</span>, <span class="st">"Pedestrian share of deaths"</span></span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Value"</span>: [</span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a>        <span class="bu">len</span>(rb_joined_11_15),</span>
<span id="cb7-41"><a href="#cb7-41" aria-hidden="true" tabindex="-1"></a>        <span class="bu">int</span>(rb_fatalities_11_15),</span>
<span id="cb7-42"><a href="#cb7-42" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>rb_share_11_15<span class="sc">:.1%}</span><span class="ss">"</span>,</span>
<span id="cb7-43"><a href="#cb7-43" aria-hidden="true" tabindex="-1"></a>        <span class="bu">int</span>(rb_injuries_11_15),</span>
<span id="cb7-44"><a href="#cb7-44" aria-hidden="true" tabindex="-1"></a>        <span class="bu">int</span>(rb_ped_deaths_11_15),</span>
<span id="cb7-45"><a href="#cb7-45" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>rb_ped_share_11_15<span class="sc">:.1%}</span><span class="ss">"</span></span>
<span id="cb7-46"><a href="#cb7-46" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb7-47"><a href="#cb7-47" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb7-48"><a href="#cb7-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-49"><a href="#cb7-49" aria-hidden="true" tabindex="-1"></a>rb_summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="33">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Metric</th>
<th data-quarto-table-cell-role="th">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Crashes matched</td>
<td>3606</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Fatalities</td>
<td>65</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Share of city fatalities</td>
<td>13.8%</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Injuries</td>
<td>4445</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>Pedestrian deaths</td>
<td>22</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>Pedestrian share of deaths</td>
<td>33.8%</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>From the above table, we can see that a total of 3606 crashes happened just between 2011 and 2015 on Roosevelt Boulevard. Out of these crashes, there were 65 fatalities. As a proportion of the total number of fatalities that have happened in Philadelphia during this time period, it is 13.8%, which accurately matches the claims made by the Philadelphia Tribune.</p>
<p>We can additionally see that there were 4445 injuries, which is more than the number of crashes, meaning on average, there was more than one person involved in each of these crashes. A more shocking figure is the number of pedestrian deaths, with there being 22 fatalities over the four year period, and indeed, the pedestrian share of deaths along Roosevelt Boulevard is 33.8%, matching the claims made by the article once again.</p>
<p>In response to these shocking figures, Philadelphia decided to implement their “Vision Zero” action plan, with the goal of “reduc(ing) Philadelphia traffic deaths to zero by 2030.” (Philadelphia Tribune). To achieve this, in June 2020, the government installed speed safety cameras along ten dangerous stretches of highway on Roosevelt Blvd, the effects of which we will see below.</p>
<div id="cell-17" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ------------------------------------------------------------</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Roosevelt Blvd share of city fatalities over time</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Uses rb_buf built above</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ------------------------------------------------------------</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> corridor_fatal_share_by_year(all_crashes_feet, corridor_buf):</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    years <span class="op">=</span> <span class="bu">sorted</span>(all_crashes_feet[<span class="st">"CRASH_YEAR"</span>].dropna().unique())</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    rows <span class="op">=</span> []</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> y <span class="kw">in</span> years:</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>        sub <span class="op">=</span> all_crashes_feet[all_crashes_feet[<span class="st">"CRASH_YEAR"</span>] <span class="op">==</span> y]</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>        city_fatal <span class="op">=</span> sub[<span class="st">"FATAL_COUNT"</span>].<span class="bu">sum</span>()</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>        j <span class="op">=</span> gpd.sjoin(sub, corridor_buf, predicate<span class="op">=</span><span class="st">"within"</span>).drop_duplicates(<span class="st">"CRN"</span>)</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>        corr_fatal <span class="op">=</span> j[<span class="st">"FATAL_COUNT"</span>].<span class="bu">sum</span>()</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>        share <span class="op">=</span> corr_fatal <span class="op">/</span> city_fatal <span class="cf">if</span> city_fatal <span class="cf">else</span> np.nan</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>        rows.append([y, corr_fatal, city_fatal, share])</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> pd.DataFrame(rows, columns<span class="op">=</span>[<span class="st">"year"</span>, <span class="st">"corr_fatal"</span>, <span class="st">"city_fatal"</span>, <span class="st">"share"</span>])</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>all_crashes <span class="op">=</span> phil_crashes_gdf.to_crs(epsg<span class="op">=</span>CRS_FEET)</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>rb_year_df <span class="op">=</span> corridor_fatal_share_by_year(all_crashes, rb_buf)</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>,<span class="dv">4</span>))</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>plt.plot(rb_year_df[<span class="st">"year"</span>], rb_year_df[<span class="st">"share"</span>], marker<span class="op">=</span><span class="st">"o"</span>)</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>plt.axvline(<span class="dv">2020</span>, linestyle<span class="op">=</span><span class="st">"--"</span>, color<span class="op">=</span><span class="st">"red"</span>, alpha<span class="op">=</span><span class="fl">0.6</span>)  <span class="co"># June 2020 cameras (year marker)</span></span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Roosevelt Blvd Share of City Fatalities Over Time"</span>)</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Share of City Fatalities"</span>)</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Year"</span>)</span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="DOW4_crash-Copy1_files/figure-html/cell-9-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The figure shows the share of all Philadelphia traffic fatalities that occurred on Roosevelt Boulevard each year. For much of the period before 2020, the boulevard consistently accounted for a substantial proportion of the city’s traffic deaths. In several years it represented more than 15 percent of all fatalities, and in some years exceeded 20 percent, reinforcing its reputation as one of the most dangerous roads in Philadelphia.</p>
<p>The dashed vertical line marks June 2020, when automated speed enforcement cameras were introduced along several segments of Roosevelt Boulevard as part of Philadelphia’s Vision Zero campaign.</p>
<p>Following the introduction of automated speed enforcement, we can see that the boulevard’s share of citywide fatalities declined significantly. While yearly values continued to fluctuate slightly, the proportion of fatalities occurring on Roosevelt Boulevard remains noticeably lower in the years after 2020 compared with many earlier years in the dataset, with a significant drop in recent years, with the share of city fatalities dropping well below 2.5%.</p>
<p>Reports from the <a href="https://philapark.org/speed-cameras/">Philadelphia Parking Authority</a> support this pattern. According to the agency, speeding tickets on Roosevelt Boulevard have fallen by 93 percent since the cameras were installed, while fatal and serious injury crashes have decreased by 21 percent and pedestrian-involved crashes have dropped by 50 percent. The apparent reduction in the boulevard’s share of city fatalities after 2020 is therefore consistent with the improvements reported following the introduction of automated speed enforcement.</p>
<p>The perceived success of the program led Pennsylvania legislators to make the camera pilot permanent and allow the city to expand automated speed enforcement to additional roadways. In 2023, the program was extended to several new roads, including sections of Route 611, which covers much of Broad Street, which we will explore next.</p>
<div id="cell-19" class="cell" data-execution_count="37">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ------------------------------------------------------------</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Broad Street: corridor buffer stats (2011–2015)</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># ------------------------------------------------------------</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>broad <span class="op">=</span> streets[</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    (streets[<span class="st">"st_name"</span>].fillna(<span class="st">""</span>).<span class="bu">str</span>.upper().<span class="bu">str</span>.strip() <span class="op">==</span> <span class="st">"BROAD"</span>) <span class="op">&amp;</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    (streets[<span class="st">"st_type"</span>].fillna(<span class="st">""</span>).<span class="bu">str</span>.upper().<span class="bu">str</span>.strip() <span class="op">==</span> <span class="st">"ST"</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>].copy().to_crs(epsg<span class="op">=</span>CRS_FEET)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>broad_buf <span class="op">=</span> gpd.GeoDataFrame(geometry<span class="op">=</span>broad.<span class="bu">buffer</span>(BUFFER_FT), crs<span class="op">=</span>broad.crs)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>city_11_15 <span class="op">=</span> phil_crashes_gdf.query(<span class="st">"2011 &lt;= CRASH_YEAR &lt;= 2015"</span>).to_crs(epsg<span class="op">=</span>CRS_FEET)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>city_fatalities <span class="op">=</span> city_11_15[<span class="st">"FATAL_COUNT"</span>].<span class="bu">sum</span>()</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>broad_joined_11_15 <span class="op">=</span> gpd.sjoin(city_11_15, broad_buf, predicate<span class="op">=</span><span class="st">"within"</span>).drop_duplicates(<span class="st">"CRN"</span>)</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>broad_fatalities_11_15 <span class="op">=</span> broad_joined_11_15[<span class="st">"FATAL_COUNT"</span>].<span class="bu">sum</span>()</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>broad_share_11_15 <span class="op">=</span> broad_fatalities_11_15 <span class="op">/</span> city_fatalities <span class="cf">if</span> city_fatalities <span class="cf">else</span> np.nan</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>broad_injuries_11_15 <span class="op">=</span> broad_joined_11_15[<span class="st">"TOT_INJ_COUNT"</span>].<span class="bu">sum</span>()</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>broad_ped_deaths_11_15 <span class="op">=</span> broad_joined_11_15[<span class="st">"PED_DEATH_COUNT"</span>].<span class="bu">sum</span>()</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>broad_ped_share_11_15 <span class="op">=</span> broad_ped_deaths_11_15 <span class="op">/</span> broad_fatalities_11_15 <span class="cf">if</span> broad_fatalities_11_15 <span class="cf">else</span> np.nan</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>broad_summary <span class="op">=</span> pd.DataFrame(</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>    {</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Metric"</span>: [</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Total Crashes"</span>, <span class="st">"Fatalities"</span>, <span class="st">"Share of city fatalities"</span>, <span class="st">"Injuries"</span>, <span class="st">"Pedestrian deaths"</span>, <span class="st">"Pedestrian share of deaths"</span>,</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>        ],</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Broad Street (2011–2015)"</span>: [</span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>            <span class="ss">f"</span><span class="sc">{</span><span class="bu">len</span>(broad_joined_11_15)<span class="sc">:,}</span><span class="ss">"</span>,</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>            <span class="ss">f"</span><span class="sc">{</span><span class="bu">int</span>(broad_fatalities_11_15)<span class="sc">:,}</span><span class="ss">"</span>,</span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>            <span class="ss">f"</span><span class="sc">{</span>broad_share_11_15<span class="sc">:.1%}</span><span class="ss">"</span>,</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>            <span class="ss">f"</span><span class="sc">{</span><span class="bu">int</span>(broad_injuries_11_15)<span class="sc">:,}</span><span class="ss">"</span>,</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>            <span class="ss">f"</span><span class="sc">{</span><span class="bu">int</span>(broad_ped_deaths_11_15)<span class="sc">:,}</span><span class="ss">"</span>,</span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a>            <span class="ss">f"</span><span class="sc">{</span>broad_ped_share_11_15<span class="sc">:.1%}</span><span class="ss">"</span>,</span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a>        ],</span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a><span class="co"># show as a clean table in notebooks</span></span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>broad_summary.style.hide(axis<span class="op">=</span><span class="st">"index"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="37">
<style type="text/css">
</style>

<table id="T_50123" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_50123_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Metric</th>
<th id="T_50123_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Broad Street (2011–2015)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_50123_row0_col0" class="data row0 col0">Total Crashes</td>
<td id="T_50123_row0_col1" class="data row0 col1">2,087</td>
</tr>
<tr class="even">
<td id="T_50123_row1_col0" class="data row1 col0">Fatalities</td>
<td id="T_50123_row1_col1" class="data row1 col1">24</td>
</tr>
<tr class="odd">
<td id="T_50123_row2_col0" class="data row2 col0">Share of city fatalities</td>
<td id="T_50123_row2_col1" class="data row2 col1">5.1%</td>
</tr>
<tr class="even">
<td id="T_50123_row3_col0" class="data row3 col0">Injuries</td>
<td id="T_50123_row3_col1" class="data row3 col1">2,284</td>
</tr>
<tr class="odd">
<td id="T_50123_row4_col0" class="data row4 col0">Pedestrian deaths</td>
<td id="T_50123_row4_col1" class="data row4 col1">13</td>
</tr>
<tr class="even">
<td id="T_50123_row5_col0" class="data row5 col0">Pedestrian share of deaths</td>
<td id="T_50123_row5_col1" class="data row5 col1">54.2%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Broad Street shows a different pattern of crash outcomes compared with Roosevelt Boulevard. Between 2011 and 2015, Broad Street recorded fewer crashes and fatalities overall, with 24 deaths and a 5.1 percent share of city fatalities, compared with 65 deaths and a 13.8 percent share on Roosevelt Boulevard. However, a much larger proportion of fatalities on Broad Street involved pedestrians. Over half of all deaths on Broad Street (54.2 percent) were pedestrians, compared with 33.8 percent on Roosevelt Boulevard. This highlights the different roles these roads play within the city. Roosevelt Boulevard functions as a wide, high-speed arterial corridor designed primarily for vehicle movement, whereas Broad Street runs through dense urban neighbourhoods with frequent pedestrian crossings and intersections.</p>
<p>This pattern is consistent with broader findings about dangerous roads in Philadelphia. According to an analysis of PennDOT crash data reported by Wapner Newman, a seven-mile stretch of Broad Street ranked among Pennsylvania’s ten deadliest road segments, with multiple fatal crashes recorded between 2015 and 2017. While Broad Street may not account for as many total fatalities as Roosevelt Boulevard, the higher share of pedestrian deaths reflects the greater interaction between vehicles and pedestrians along one of the city’s busiest urban roadways.</p>
<div id="cell-21" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ------------------------------------------------------------</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Broad Street share of city fatalities over time</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># ------------------------------------------------------------</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>broad_year_results <span class="op">=</span> []</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> y <span class="kw">in</span> years:</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    subset <span class="op">=</span> all_crashes[all_crashes[<span class="st">'CRASH_YEAR'</span>] <span class="op">==</span> y]</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    b_fatal, city_fatal, share <span class="op">=</span> corridor_stats(subset, broad_buf)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    broad_year_results.append([y, b_fatal, city_fatal, share])</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>broad_year_df <span class="op">=</span> pd.DataFrame(broad_year_results, columns<span class="op">=</span>[<span class="st">'year'</span>,<span class="st">'broad_fatal'</span>,<span class="st">'city_fatal'</span>,<span class="st">'share'</span>])</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>,<span class="dv">4</span>))</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>plt.plot(broad_year_df[<span class="st">'year'</span>],</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>         broad_year_df[<span class="st">'share'</span>],</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>         marker<span class="op">=</span><span class="st">'o'</span>,</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>         color<span class="op">=</span><span class="st">'darkgreen'</span>,</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>         label<span class="op">=</span><span class="st">'Broad Street share of city fatalities'</span>)</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a><span class="co"># vertical line for enforcement policy</span></span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>plt.axvline(<span class="dv">2025</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, color<span class="op">=</span><span class="st">'blue'</span>, alpha<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a><span class="co"># annotation explaining the policy</span></span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>plt.text(<span class="fl">2025.1</span>,</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>         broad_year_df[<span class="st">'share'</span>].<span class="bu">max</span>()<span class="op">*</span><span class="fl">0.9</span>,</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>         <span class="st">"Speed cameras installed</span><span class="ch">\n</span><span class="st">Sept 15, 2025</span><span class="ch">\n</span><span class="st">Fines begin Nov 14, 2025"</span>,</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>         fontsize<span class="op">=</span><span class="dv">9</span>,</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>         color<span class="op">=</span><span class="st">'blue'</span>)</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Broad Street Share of City Fatalities Over Time"</span>)</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Share of City Fatalities"</span>)</span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Year"</span>)</span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="DOW4_crash-Copy1_files/figure-html/cell-11-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>https://6abc.com/post/broad-street-speed-cameras-activated-philadelphia-drivers-face-100-ticket/18154437/</p>
<p>The figure above shows the share of all Philadelphia traffic fatalities occurring on Broad Street over time. For much of the early and mid-2000s, Broad Street consistently accounted for between 3 and 8 percent of the city’s annual fatalities. While this share fluctuated from year to year, the overall values remained noticeably lower than those observed on Roosevelt Boulevard, reflecting the smaller number of total fatal crashes recorded along the corridor.</p>
<p>However, in more recent years the share increased noticeably, with several years after 2020 exceeding 8–11 percent of citywide fatalities. This upward trend explains why Broad Street had become a growing focus of traffic safety efforts within Philadelphia. As one of the city’s busiest north–south corridors passing through center city, the road experiences heavy vehicle traffic alongside significant pedestrian and cyclist activity, creating conditions where severe crashes can occur.</p>
<p>In response to these concerns, the city introduced automated speed enforcement along Broad Street, with cameras installed at 15 intersections along North and South Broad Street. According to a report by <a href="https://6abc.com/post/broad-street-speed-cameras-activated-philadelphia-drivers-face-100-ticket/18154437/">6abc Philadelphia</a>, the cameras became fully operational in November 2025, after a 60-day warning period, with drivers caught exceeding the speed limit by more than 11 mph receiving fines starting at $100. According to the report, officials hope that the cameras will reduce speeding and improve safety in the same way that automated enforcement did on Roosevelt Boulevard, where violations dropped dramatically and pedestrian crashes declined significantly.</p>
<p>Although the data shown in the figure predates the full implementation of the Broad Street camera program, the trend highlights why the road became a priority for intervention. By targeting high-risk roads where fatalities represent a growing share of citywide incidents, automated speed enforcement is able to potentially reduce dangerous driving behaviour and improve safety for both drivers and pedestrians.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/dpark2380\.github\.io\/comm3180_S26_Blog\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>